aleph-im/pyaleph

src/aleph/config.py

The default port for MongoDB is 27017, not 27006.
https://docs.mongodb.com/manual/reference/default-mongodb-port/
Solution: Use the default port 27017

Problem: Config requires changing port for MongoDB

---

deployment/docker-demo/debug.sh
src/aleph/commands.py
src/aleph/services/p2p/__init__.py
src/aleph/services/p2p/manager.py

Problem: Storing node private key the config is not always secure
Solution: Allow loading the node key pair from a dedicated file, and writing it to a file upon generation.
The main goal is to force persistence of the private key, so restarting a node will not change the key pair every time.

Store node private key in a file

---

src/aleph/commands.py

pyaleph raises the following error when launched:
`argparse.ArgumentError: argument --host/-h: conflicting option string: -h`
Solution: Rename -h and --host to -b and --bind
Issue introduced by #19

Problem: CLI arg -h conflicts with --help

---

src/aleph/chains/__init__.py

Solution:
- Do not print tracebacks for these expected errors
- Only catch relevant exceptions, not anything
- Use a logger instead of printing

Problem: Stacktraces worrying when not all chain libraries installed

---

.dockerignore
deployment/docker-demo/Dockerfile
deployment/docker-demo/README.md
deployment/docker-demo/build.sh
deployment/docker-demo/entrypoint.sh
deployment/docker-demo/run.sh
deployment/docker-demo/supervisord.conf

This adds a `Dockerfile` with helper scripts and a README to run PyAleph as a monolothic Docker image for demo purposes.
To run this image, you will need a PyAleph configuration file, as that file contains private keys.
Nothing else should be required to run a node.

Monolithic Docker image for easy demo node setup 

---

setup.cfg

Some dependencies have version conflicts, and some dependencies are mentionned explicitely in the `README.md` instead of being in the setup.cfg
Solution: Fix the version of dependencies requiring a minimum version number, and use the forks of dependencies in setup.cfg where they are necessary.

Problem: Dependencies not working out of the box

---

src/aleph/services/ipfs/pubsub.py

Problem: Infinite loop filled logs when IPFS not available
PyAleph tried to connect to IPFS in an infinite loop with
no delay when connection failed, resulting of high CPU
and log usage.
Solution: Add a 2 seconds delay on reconnection and only catch ConnectionRefusedError.

Infinite loop when IPFS not available

---

.github/workflows/build-docker-demo.yml
deployment/docker-demo/Dockerfile
deployment/docker-demo/README.md
deployment/docker-demo/build.sh
deployment/docker-demo/config.yml
deployment/docker-demo/debug.sh
deployment/docker-demo/run.sh
deployment/docker-demo/supervisord.conf

Remove the hardcoded use of Podman to allow use of Docker.
Fix issues in various files.
Add Docker build in GitHub Actions so the image will be easy to run without cloning this repo.

Enh docker demo

---

.dockerignore
.gitignore
deployment/docker/Dockerfile
deployment/docker/README.md
deployment/docker/build.sh
deployment/docker/config.yml
deployment/docker/docker-compose.yml

**Problem**: Dockerfile was absent to run PyAleph for production mode
**Solution**: Add a Dockerfile to run PyAleph in a production mode, as well as a docker-compose.yml file to document how to run it and allow running the node with Docker Compose.

Add Docker and Docker Compose files

---

src/aleph/commands.py

This is an issue for backward compatibility
Solution: Only try to load the private key from a file if it is absent from the configuration file.

Problem: Key from config was ignored by default

---

.github/workflows/build-docker.yml
deployment/docker-build/Dockerfile
deployment/docker-build/README.md
deployment/docker-build/build.sh
deployment/docker-build/config.yml
deployment/docker-build/docker-compose.yml
deployment/docker-compose/README.md
deployment/docker-compose/docker-compose.yml
deployment/docker-demo/build.sh
deployment/docker-demo/debug.sh
deployment/docker-demo/run.sh
docs/guides/docker-compose.rst
docs/guides/index.rst
docs/index.rst

This is a proposal for the deployment of official Aleph Nodes using PyAleph, using Docker and Docker-Compose.
The file `docs/guides/docker-compose.rst` documents how to install, setup and run an Aleph Node using official Docker images published by Aleph.im on the Docker Hub.
The Docker tag documented is currently `alephim/pyaleph-node:beta` to indicate that it is not considered ready for prime time yet.
This proposal also adds GitHub Actions workflows to build Docker images of PyAleph. These builds will be used for CI, but cannot be pulled by end users yet as this will require [migrating to GitHub Container Registry for Docker images](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-ima …

Deploy Aleph Nodes using Docker and build Docker images in GitHub Actions

---

requirements.txt
setup.cfg
src/aleph/commands.py

Solution: Use library `setproctitle` to rename multiprocessing processes in a meaningful way.

Problem: Different processes were hard to differentiate

---

deployment/docker-build/Dockerfile
deployment/docker-demo/Dockerfile

Solution: Reinstall aiohttp with pip after installing requirements.
This appears to solve the issue, but the reason is not known.

Problem: Aiohttp ports 4024 and 8080 are not working.

---

.dockerignore

The folder `src/pyaleph.egg-info` is copied on the build, at least using Podman, and the build fails as it should not be present yet.
Solution: Add the pattern to .gitignore

Problem: Docker build fails after using for debug

---

src/aleph/chains/__init__.py
src/aleph/commands.py
src/aleph/jobs.py
src/aleph/network.py
src/aleph/services/ipfs/pubsub.py
src/aleph/services/p2p/__init__.py
src/aleph/services/p2p/manager.py
src/aleph/services/p2p/protocol.py

It is recommended to use asyncio.run_until_complete(asyncio.gather(coroutines)) instead of creating tasks on the loop singleton and then running it _forever_.
Solution: Put coroutines to execute in lists, gather them together and run them all at once.

Problem: asynciocreate_task is hard to understand

---

src/aleph/web/controllers/main.py
src/aleph/web/templates/index.html

Solution: Push new messages and pending_messages counts via WebSocket.
This is still a basic implementation, as moving to more complex UI (Vue, ...) is not needed yet.

Problem: Updating msg count required page reload

---

src/aleph/web/controllers/main.py
src/aleph/web/controllers/metrics.py
src/aleph/web/templates/index.html
tests/web/controllers/test_metrics.py

Problem: Operator could not get metrics
Solution: Implement a Prometheus entrypoint on `/metrics` and expose aleph node metrics on it.
The following metrics are exposed:
```
pyaleph_build_info{python_version="3.8.5",version="unknown"} 1
pyaleph_status_sync_messages_total 71896
pyaleph_status_sync_pending_messages_total 421233
```

Add Prometheus /metrics entrypoint

---

src/aleph/commands.py

Solution: Load the configuration from file before
starting to use it for p2p keys.

Fix: Config was used before being loaded from file

---

docs/guides/docker-compose.rst

Sentry.io provides an easy way to track errors in processes without having to look at the serial output.
Errors can then be analyzed via a web interface and operators notified by email or other channels.
This adds the option to enable sending errors to Sentry, as well as a CLI argument to disable it.

Feature: Add Sentry error tracking

---

deployment/docker-build/docker-compose.yml
deployment/docker-compose/docker-compose.yml

Version 2.4 was not needed, and prevents operators to deploy nodes on Ubuntu 18.04.
Fixes #54

Allow docker-compose format 2.2

---

.github/workflows/build-docker-demo.yml
.github/workflows/build-docker.yml
src/aleph/__init__.py

Command "git describe --tags" gives an output in the form "v0.0.1" or "v0.0.1-abcdefgh", where "v0.0.1" is the name of the last tag and "abcdefgh" is the start of the last commit id.
Related to #72

Feat: Use git tags for version numbers

---

src/aleph/jobs.py

The queue `gtasks` used to grow so much that it was not processed before the memory of the node was exhausted.
This fixes the issue by using smaller batches.
Related to #71

Fix: Process smaller groups of tasks (gtasks)

---

setup.cfg

Include a fix to use sets instead of lists for peers, and fix a dependency issue when used with pyaleph.
This seems to work, and seems more reliable than merging all commits from 0.1.4 on top of the fork of PyAleph.
Closes #47

Upgrade libp2p to version 0.1.4 with 2 fixes

---

deployment/docker-monitoring/READMEs.md
deployment/docker-monitoring/docker-compose.yml
deployment/docker-monitoring/grafana/dashboard.yaml
deployment/docker-monitoring/grafana/dashboards/aleph/dashboard.json
deployment/docker-monitoring/grafana/dashboards/node/dashboard.json
deployment/docker-monitoring/grafana/prometheus.yaml
deployment/docker-monitoring/prometheus.yml

This adds an easy way to monitor an Aleph node, via a `docker-compose.yml` and configuration files for Grafana and Prometheus.

Feature: Add containers for node monitoring

---

setup.cfg

Since aleph-client has been upgraded, there is no need to rely on GitHub for it anymore.

Chore: Install aleph-client from PyPI

---

src/aleph/web/controllers/p2p.py

A client was only receiving {status: failed} on pub errors of any kind.
This change lets the client know which pub mechanism failed, and returns an error 500 if both failed.

Feature: Publication errors were too vague

---

deployment/docker-build/Dockerfile
deployment/docker-demo/Dockerfile

It required executing the container to run `pip freeze` in it.
Solution: Run `pip freeze` during build and save the output in a file.
In the future, this it will be possible to compare this with a list of frozen requirements to find issues due to upgrades in dependencies.

Problem: Could not easily list installed Python packages

---

src/aleph/network.py
src/aleph/services/ipfs/pubsub.py
src/aleph/services/p2p/protocol.py

Removed the `base_url` parameter from `services.ipfs.pubsub` as
it was unused. Cleaned the callers.

[Fix] Remove unused parameter in IPFS sub function

---

deployment/docker-build/pyaleph.dockerfile
deployment/scripts/extract_requirements.py

Modified the PyAleph Dockerfile to separate the install of
the dependencies from PyAleph itself. This way, we can install
the requirements once and cache them in a layer of the image,
avoiding to fetch them each time.
A new script, `extract_requirements.py`, is used to read
the install requirements from setup.cfg into a temporary
requirements.txt file.
Removed the install of pytest from the Docker image as it is
not relevant to a Docker image.

[Setup] Install dependencies early in Dockerfile

---

src/aleph/commands.py
src/aleph/jobs.py
src/aleph/network.py
src/aleph/services/p2p/__init__.py
src/aleph/services/p2p/jobs.py
src/aleph/services/p2p/manager.py
src/aleph/services/p2p/peers.py
src/aleph/services/p2p/protocol.py
src/aleph/services/p2p/pubsub.py
src/aleph/services/p2p/singleton.py
src/aleph/storage.py
src/aleph/web/controllers/p2p.py

Moved most calls to singleton variables higher in the call stack
to improve the testability of the P2P functions. These singletons
will be completely eliminated in future PRs.

[P2P] Access singletons higher in the call stack

---

.github/workflows/pyaleph-ci.yml

Added a mechanism to cache Docker images after build to speed up
the next CI run. The mechanism is similar to what was done in
the previous CI but uses the new Github Container Registry
instead of the deprecated Docker Registry.

[CI] Cache Docker images

---

.github/workflows/pyaleph-ci.yml
setup.cfg
src/aleph/services/p2p/jobs.py
src/aleph/services/p2p/peers.py
src/aleph/services/p2p/protocol.py
src/aleph/services/p2p/pubsub.py
src/aleph/storage.py
src/aleph/web/controllers/p2p.py
tests/p2p/conftest.py
tests/p2p/test_connect.py
tests/p2p/test_identify.py
tests/p2p/test_pubsub.py

Added tests for the P2P service. We now test the connection and
pubsub functionalities.
The new tests spawn JS P2P daemons and act as simplified nodes
exchanging messages. We test the following features:
* connection to a remote node
* exchange of "hello" messages
* subscription and publication of messages on P2P topics.
The tests for the P2P streaming protocol will follow after a bug
within p2pclient and/or the P2P daemon is fixed.

[P2P] Added tests and fixed issues

---

src/aleph/jobs.py
src/aleph/model/pending.py

We observed that some messages fail being processed correctly many times. This could be due to temporary issues and the message should still be processed and not ignored.
In order to prevent these messages from obstructing other messages to be processed, this change sorts the pending messages during processing by the ascending number of retries, such that messages that have now or little been retried are processed first.
This should improve the responsiveness of the nodes when processing new messages.

Change: Sort pending messages by number of retries in processing

---

src/aleph/commands.py
src/aleph/exceptions.py

The "protocol" client type is not supported at the moment due
to a bug within the JS P2P daemon. Added an error message and
stopped the node early if someone attempts to use it.

[Config] Disable "protocol" P2P config

---

src/aleph/network.py
src/aleph/services/ipfs/pubsub.py
tests/chains/test_common.py

Modified the message validation procedure so that an incorrect
signature results in an `InvalidMessageError` being thrown.
This fixes an issue where the verification would fail silently
and propagate a null value.

[Messages] Raise exception on signature verification failure

---

src/aleph/web/controllers/metrics.py
src/aleph/web/templates/index.html

Fixed two issues in the index page of the node.
* Fixed an issue where the number of remaining blocks to integrate
could be negative. This happened because we compare the last
block holding Aleph data with the total height of the blockchain.
As some blocks do not contain Aleph data, the balance could
become negative. Floored the balance to 0 to avoid the issue.
* Fixed an issue in the progress bar where the current height was
not divided by the total height, resulting in an incorrect
progress status.

[Index] Fix minor issues

---

src/aleph/web/controllers/messages.py

Added the `startDate` and `endDate` parameters to
`KNOWN_QUERY_FIELDS`.
Fork of #160 with rebase to `origin/dev`

[API] Add start/end dates to message schema

---

deployment/docker-compose/docker-compose.yml

Fixed an error that went through with the updater PR. Reverted
unwanted changes to the dependencies of the pyaleph and p2pd
services in the Docker Compose file.

[Fix] Remove nonexisting dependencies in Docker Compose

---

src/aleph/web/controllers/metrics.py

Fixed a regression that would cause the ETH remaining height value
to be set to None instead of 0.

[Metrics] Avoid null value when chain height is 0

---

src/aleph/commands.py
src/aleph/jobs.py
src/aleph/services/p2p/__init__.py

The web server processes must initialize all the global variables
(DB, IPFS, P2P) on their own. The function used to initialize
the P2P system would also spawn the subscriber tasks. The API
only needs to be able to write to the P2P pubsub topics.
Moved the initialization of the singleton P2P client in
the `init_p2p_client` function and used that function instead
of `init_p2p` in API processes.

[P2P] Do not run P2P tasks in web servers

---

docs/conf.py
docs/protocol/messages/index.rst
setup.cfg
src/aleph/services/keys.py

Fixed all the warnings that popped up when building the docs:
* Removed all references to recommonmark as it is now deprecated
and unused in the project anyway
* Removed the empty take.rst file
* Fixed index issues in docs/protocol/messages
* Fixed indentation issues in a docstring.

[Doc] Fix warnings

---

src/aleph/model/pending.py

Fixed an issue where this index would not be used by the query
listing pending messages because the query looks for all messages
and not only those who have already been retried. This would result
in a memory error with MongoDB given the number of pending messages.

[DB] Remove partial attribute on retries + time index

---

docs/conf.py
docs/guides/install.rst
docs/guides/upgrade.rst

Modified all links pointing to the git repository to make them
point to the latest released version instead of master.

[Docs] Use version in download links

---

deployment/migrations/scripts/0002-refresh-chain-pins.py

This solves an issue where existing nodes would not create PermanentPin documents for chaindata that has already been processed.
To achieve this, it resets the chaindata height so that all chaindata is processed once more by the node.

Fix: All PermanentPin were only created on new nodes

---

src/aleph/services/utils.py
tests/services/test_utils.py

On some servers, get_IP() returned chinese chars instead if a proper IPv4. This protects against invalid IP formats.

Fix: Protect against wrong IPv4 format from 3rd party service.

---

docs/guides/upgrade.rst

Fixed an issue in the upgrade guide where the node-secret.key file
was not accessible from the Docker container. Fixed the issue by
copying the key in the keys directory before launching the upgrade.

[Doc] Upgrade: add node-secret.key to keys directory

---

src/aleph/services/p2p/protocol.py
src/aleph/services/peers/monitor.py
src/aleph/services/utils.py

Fixed an issue where a PSMessage instance was treated as a dict.
The easiest fix is to translate this object to a dictionary to
maintain compatibility.

[Fix] Translate pubsub message to dict early

---

docs/guides/install.rst
docs/guides/upgrade.rst

Solution: Use the current release tag instead.

Fix: The `beta` docker image was used only for `chown`

---

.readthedocs.yml
README.md

With both Ubuntu 20.04 LTS and Debian 11 ship Python 3.8, and most deployments using containers, there is no valid reason to keep supporting older versions of Python.

Change: Drop support for Python 3.6, require 3.8+

---

setup.cfg

Fixed warnings coming from aiocache complaining about not being
able to import ujson and msgpack.

[Dependencies] Install ujson and msgpack for aiocache

---

src/aleph/services/ipfs/storage.py

Solution: Use the timeout when getting the IPFS data using `ipfs_api.cat(...)`.

Fix: get_ipfs_content ignored the `timeout` argument

---

src/aleph/chains/common.py
src/aleph/exceptions.py
src/aleph/handlers/forget.py
src/aleph/handlers/storage.py
src/aleph/services/ipfs/common.py
src/aleph/services/p2p/protocol.py
src/aleph/storage.py
src/aleph/web/controllers/storage.py
tests/storage/test_get_content.py

Simplified the storage code and made it more pythonic by replacing
status codes like None and -1 by exceptions. Two new exceptions
describe if the content the user is looking for is invalid (-1)
or just currently unavailable because of a synchronisation issue
or a technical issue (None).
This simplifies the whole logic and avoids the propagation of weird
codes all over the place.
Added new dataclasses to keep track of the retrieved content,
its hash and the source from which the data was fetched.
The `RawContent` class keeps track of binary content while
the `JsonContent` class represents raw content that was interpreted
as JSON.

[Storage] Rewrite status codes as exceptions

---

src/aleph/services/p2p/protocol.py

Implemented a workaround to avoid spamming exception logs when
the communication with the P2P daemon enters an invalid state
and spams IncompleteRead exceptions. The exceptions are now
buffered until reaching a threshold (30000 exceptions).

[Fix] Buffer P2P incomplete read errors

---

src/aleph/handlers/storage.py
tests/storage/conftest.py
tests/storage/test_get_content.py
tests/storage/test_store_message.py

Mirrored the validation system used for forget messages in store
messages. Used the `StoreMessage` class to validate the message
and content dictionaries.
We now discard the message if it fails validation instead of
retrying it through the default exception handler. This fixes
an issue where invalid store messages would be retried indefinitely.
Added unit tests for the storage handler.

[Storage] Use Aleph message model for validation

---

src/aleph/services/p2p/jobs.py
src/aleph/services/p2p/manager.py

Simplified the job by providing the config as an argument instead
of letting the function find it.

[Cleanup] Provide config to tidy peers job

---

src/aleph/commands.py
src/aleph/jobs.py

The message processing loop now requires the `shared_stats` dict
to be non-null.

[Typing] Make shared stats non-optional

---

src/aleph/chains/common.py
src/aleph/jobs.py

Fixed two issues related to the pending TX process/job:
1. Exceptions occurring inside the job would sometimes
be suppressed because of the use of `return_exceptions`
in asyncio.gather. All exceptions are now logged.
2. The api_servers shared list is now passed as argument
to the job on startup, allowing the job to fetch
message content from the network.

[TX handler] Various fixes

---

src/aleph/services/p2p/protocol.py
src/aleph/services/peers/monitor.py

Improved the threshold mechanism for incomplete read errors linked
to the P2P daemon that sometimes occur over long periods of time.
* Added a sleep of 2 seconds before the next reconnection attempt
* Adapted the threshold so that a log is sent approximately every
10 minutes
* Added a retry to some monitoring jobs that were not restarted
after the first failure.

[P2P] Reduce amount of logs in case of errors

---

src/aleph/chains/common.py
src/aleph/exceptions.py
src/aleph/handlers/storage.py
src/aleph/jobs.py
src/aleph/network.py
src/aleph/services/ipfs/pubsub.py
src/aleph/services/p2p/protocol.py
src/aleph/types.py
src/aleph/web/controllers/storage.py
tests/storage/test_store_message.py
tests/test_network.py

Put exception code in the right place.

[Exceptions] Move old exceptions from types to exceptions

---

CHANGELOG.rst
src/aleph/chains/common.py
src/aleph/jobs.py
src/aleph/model/db_bulk_operation.py
src/aleph/services/ipfs/pubsub.py
tests/chains/test_common.py
tests/test_network.py

Improved the `incoming` function to simplify it and make it more
generic.
Removed the `bulk_operation` flag as we always wish for bulk DB
operations. The function now returns a status + a list of DB
operations. DB operations are a new class that contains a Mongo
operation and the name of the collection to target.
This avoids passing lists as arguments and modifying them in place.
The loop to await individual message tasks now waits for all tasks
to complete instead of failing on the first operation.
This fixes an issue where, if an exception occurs soon enough in
the batch, the output of still-running tasks could be lost.
Added type hints.

[Processing] Simplify incoming message functions

---

.github/workflows/pyaleph-ci.yml
tests/conftest.py
tests/message_processing/fixtures/test-data-pending-tx-messages.json
tests/message_processing/test_process_pending_txs.py

Added a fixture to initialize the database. This fixture initializes
the collections used by a CCN in a separate database and resets
it on every run.
This feature will allow to write more extensive tests by preloading
fixture data in the DB.
Implemented a first test using the fixture for the pending TX job.
On the CI side, we now spawn a service container to run MongoDB.

[Tests] Database support in tests

---

src/aleph/chains/common.py
src/aleph/chains/ethereum.py
src/aleph/chains/nuls2.py
src/aleph/commands.py
src/aleph/config.py
src/aleph/handlers/storage.py
src/aleph/jobs/job_utils.py
src/aleph/jobs/process_pending_messages.py
src/aleph/jobs/process_pending_txs.py
src/aleph/model/__init__.py
src/aleph/network.py
src/aleph/services/filestore.py
src/aleph/services/ipfs/common.py
src/aleph/services/ipfs/storage.py
src/aleph/services/p2p/manager.py
src/aleph/storage.py
src/aleph/utils.py
src/aleph/web/controllers/metrics.py
tests/storage/conftest.py

Removed all dependencies to the aiohttp app object in non-API code.
This object was used all over the place to retrieve the config
object. Instead, we now use a global variable to store the config
object itself.

 [Config] Remove dependency to API in non-API code

---

src/aleph/chains/common.py
src/aleph/chains/ethereum.py
src/aleph/chains/nuls2.py
src/aleph/chains/tx_context.py
src/aleph/jobs/process_pending_txs.py

The new `TxContext` class encapsulates metadata regarding chain
transactions.

[Types] New dataclass for tx context

---

src/aleph/chains/common.py
src/aleph/jobs/job_utils.py
src/aleph/jobs/process_pending_messages.py
src/aleph/jobs/process_pending_txs.py
src/aleph/toolkit/batch.py
tests/message_processing/conftest.py
tests/message_processing/load_fixtures.py
tests/message_processing/test_perform_db_operations.py
tests/message_processing/test_process_pending_txs.py
tests/utils/test_batch.py

Simplified the pending TXs code. The task to handle a single TX
is now stateless and returns a list of DB operations.
The processing of DB operations is now the same for pending TXs
and messages.
Added a new `async_batch` method to group TXs by batch.

[Jobs] Simplify pending TXs job

---

src/aleph/chains/common.py

Fixed a warning that occurs in the TX processing loop. The logs
warn about not being able to pin the chaindata files:
Can't pin hash Qm...
The files end up being pinned anyway, the operation just takes
longer than 4 seconds. As we now know, some IPFS fetches can take
up to 100s of seconds. Increased the timeout to 2 minutes to
silence the warning.

[TXs] Increase IPFS pin timeout to 2 minutes

---

src/aleph/commands.py
src/aleph/jobs/process_pending_messages.py
src/aleph/jobs/process_pending_txs.py

Fixed an omission, pass the actual value of the config option
when starting subprocesses. This issue caused the subprocesses
to crash at boot.

[Logging] Use property value for max_log_file_size

---

deployment/migrations/config_updater.py
deployment/migrations/scripts/0002-refresh-chain-pins.py

The config updater now detects if the upgrade/downgrade functions
are regular functions or coroutines and executes them the right
way, reducing the amount of boilerplate required.
We now initialize the global variables to access MongoDB directly
from the main script of the config updater.

[Migrations] Support for async upgrade functions

---

src/aleph/chains/common.py
tests/chains/test_confirmation.py

Fixed an issue where the message processing job would fail while
writing a confirmation to the capped messages collection.
In MongoDB, it is not possible to increase the size of a document
in a capped collection. As this particular collection is only used
for the websockets to advertise new messages, we now simply
ignore the confirmation for this collection.
Added a unit test to test the confirmation flow.

[Messages] Ignore confirmations in capped collection

---

deployment/migrations/config_updater.py

Added a filter to run only specific migration scripts using a
glob expression. This is especially useful for development
purposes when testing a new script.

[Migrations] Filter to select migration scripts

---

src/aleph/commands.py
src/aleph/web/__init__.py
tests/api/fixtures/fixture_messages.json
tests/api/test_messages.py
tests/api/test_version.py

Added basic tests for the /api/v0/messages.json endpoint.
Improved the app creation flow: we now create the app inside
the `create_app` function. This is required to run several
API unit tests, as pytest resets the event loop on each run.

[Tests] Messages API tests

---

src/aleph/services/ipfs/storage.py
src/aleph/storage.py
src/aleph/web/controllers/ipfs.py
src/aleph/web/controllers/storage.py

The name of the file uploaded through IPFS and storage endpoints
is useless because we only rely on hashes.

[Storage] Remove filename parameter

---

tests/storage/forget/test_forget_message.py

Fixed the fixtures in the basic forget tests. Some were missing
the content field, making the test succeed for the wrong reason
(this looked like the message was already forgotten).
Another fixture was using the wrong sender ID, but worked for
similar reasons.
The tests now work as expected.

[Tests] Use valid fixtures in forget tests

---

src/aleph/web/controllers/messages.py
tests/api/test_messages.py

Users can now specify one or more chains to filter messages
in the messages API.

[API] Add chain query parameter for messages

---

src/aleph/model/messages.py
src/aleph/web/controllers/messages.py
tests/api/test_messages.py

Users can now specify one or more content hashes to filter
messages in the message API with the new `contentHashes`
query parameter. This new parameter filters messages
on their `content.item_hash` field.

[API] Add content hash query parameter for messages

---

tests/api/test_messages.py
tests/api/test_version.py
tests/conftest.py

Added the new `ccn_api_client` fixture to put the API test client
code in one place. We now set the event loop in debug mode
to return the stack trace on 500 errors.

[Tests] Fixture to generate the test API client

---

src/aleph/handlers/forget.py
src/aleph/handlers/storage.py
src/aleph/jobs/process_pending_messages.py
src/aleph/network.py
src/aleph/storage.py
src/aleph/types.py
src/aleph/utils.py
src/aleph/web/controllers/storage.py
tests/storage/test_get_content.py

Removed the `ItemType` enum and replaced all usages by the equivalent
class in aleph-message.

[Types] Use ItemType defined in aleph-message

---

deployment/docker-build/pyaleph.dockerfile
deployment/samples/docker-monitoring/grafana/dashboards/aleph/dashboard.json
src/aleph/commands.py
src/aleph/config.py
src/aleph/jobs/__init__.py
src/aleph/jobs/job_utils.py
src/aleph/jobs/process_pending_messages.py
src/aleph/jobs/process_pending_txs.py
src/aleph/toolkit/split.py
src/aleph/web/controllers/metrics.py
tests/web/controllers/test_metrics.py

Several improvements to the pending TX/message jobs.
* The jobs used to work by batch, meaning they started a series
of N tasks and then waited for these tasks to finish before
starting the next batch. This has the obvious disadvantage
that the job ends up waiting on the slower tasks, while other
tasks could have been started earlier. The jobs now have a
max concurrency parameter that limits the total number of tasks.
The job will automatically collect any finished task and spawn
new ones up until the limit.
* Refactored the message processing job to get rid of the i/j
logic that modified the batch size depending on whether the job
was processing STORE messages. The job now uses a system of
semaphores per message type that can limit the number of tasks
running in parallel for a specific …

[Messages] Improve throughput of jobs

---

src/aleph/network.py
src/aleph/schemas/pending_messages.py
tests/schemas/test_pending_messages.py
tests/test_network.py

Added new Pydantic models/schemas to validate Aleph messages
coming from the network. These models are similar to the ones
implemented in aleph-message, but focus on validating messages
before processing them.
This validation replaces the validation in check_message
and will later be used to use objects as early as possible
in the processing of messages.
Added tests for the major types of messages.
Breaking changes (to validate):

[Messages] Pydantic schema for message validation

---

src/aleph/handlers/forget.py
tests/storage/forget/test_forget_message.py

Reduced the data usage of the forget handler in two ways.
1. Stop relying on `get_message_content` to retrieve the content
of a message. As the message is guaranteed to already be on
the node, we can directly get the parts of interest from the DB.
2. Only retrieve the fields relevant to the handling of the forget
message from the DB. Rather than retrieving the whole content,
which can be quite large, we now only retrieve the address, item
type and item hash from the DB. This should improve the performance
of the handler. Introduced a new class, `TargetMessageInfo`, to
represent the data we fetch from the DB.

[Forget] Fetch less data

---

src/aleph/chains/avalanche.py
src/aleph/chains/common.py
src/aleph/chains/cosmos.py
src/aleph/chains/ethereum.py
src/aleph/chains/nuls.py
src/aleph/chains/nuls2.py
src/aleph/chains/solana.py
src/aleph/chains/substrate.py
src/aleph/network.py
src/aleph/register_chain.py
tests/chains/test_common.py
tests/chains/test_substrate.py

We now use the `BasePendingMessage` class in the signature verifiers
for all supported chains.
Modified some tests since we can now make some hypotheses about
fields being present (and valid) in the message object.

[Chains] Use pending message model in signature verification

---

src/aleph/schemas/pending_messages.py
tests/schemas/test_pending_messages.py

Some messages do not provide the `item_type` field.
Added logic in the first validator of the `PendingMessage` schema
to set it to a default value based on the value of `item_content`
and `item_hash` if necessary.

[Messages] Support default item type

---

setup.cfg

The dependency to determine the version of aleph-message was
missing and only relied on the dependency through aleph-client.

[Dependencies] Add dependency to aleph-message

---

deployment/samples/docker-monitoring/grafana/dashboards/aleph/dashboard.json

Set the Prometheus dashboard back to showing the last 6 hours
of data, and reset the refresh rate to 10 seconds. Moved some
panels that did not appear in the right place.

[Monitoring] Fix Grafana dashboard time ranges

---

docs/protocol/messages/aggregate.rst
docs/protocol/messages/forget.rst
docs/protocol/messages/index.rst
docs/protocol/messages/post.rst
docs/protocol/messages/program.rst
docs/protocol/messages/store.rst

Documented the different message types and the use of the message
fields.

[Docs] Improve protocol documentation

---

setup.cfg
src/aleph/handlers/forget.py

Added support for the new `aggregates` field in FORGET messages.
Using this field, users can now specify one or more aggregates
to forget. This will lead to the deletion of all the messages
linked to these aggregates.
For now, the implementation simply lists all the messages stored
on the node and deletes them.

[Forget] Forget aggregates

---

docs/guides/upgrade.rst

The new Dockerfile sets the entrypoint to the startup script.
This fix tells users how to override this entrypoint to run
migrations when upgrading a node.

[Doc] Fix upgrade guide for migrations

---

src/aleph/network.py
src/aleph/storage.py

Fix for a regression in the message validation. If the user did
not specify the item type of the message, the default value was
not added to the message anymore, resulting in errors down
the line.

[Fix] Set default item_type in messages

---

src/aleph/chains/common.py
src/aleph/network.py

Fix for the previous fix. Some messages end up with check_message
set to False, bypassing the validation in `incoming`. We now
set the default value of `item_type` as the first thing in
the function.
Note that this is a temporary fix that will disappear as soon
as we use Pydantic models everywhere.

[Fix] Set default item type early

---

deployment/docker-build/README.md
docs/guides/install.rst
docs/guides/upgrade.rst

Fixed a regression in the doc. The docker commands were not taking
the Docker entrypoint into account. We now reset the entrypoint
to the default value to launch specific commands with the Docker
image.

[Doc] Update doc to generate node keys

---

src/aleph/jobs/process_pending_messages.py

Fixed an issue where the pending message job would block on
the final messages in the queue and stop processing newer messages.
Once the job finishes the loop on all the messages in the pending
message collection, the previous implementation waits until all
the message tasks finish. This causes a delay of several hours
until the node finishes these tasks and is able to process newer
pending messages again. Messages end up being processed, but far
later than expected.
The issue arises because we never remove messages from the pending
queue if we fail to retrieve the associated content. The job
then always has messages in the queue, causing the issue.
Fixed the issue by allowing the loop to restart without waiting
for messages to be processed. We now compute an individual ID
for each …

[Messages] No blocking on end of queue

---

tests/p2p/test_connect.py
tests/p2p/test_identify.py
tests/p2p/test_pubsub.py

A dependency issue occurred on npm and makes the P2P tests fail
for a reason that has yet to be determined. Skip the tests for now.

[Tests] Skip tests relying on the P2P daemon

---

src/aleph/chains/avalanche.py

Display "Avalanche" instead of "Solana" when validations fails for an Avalanche message.

fix: (minor) Validation typo

---

src/aleph/web/controllers/p2p.py
tests/web/controllers/test_pub_json.py

Fixed an issue where the validation of messages performed
in the P2P endpoints would not deserialize the message beforehand.
This led to all messages being rejected.

[Messages] Fix validation of P2P messages

---

.gitignore

Setup instructions boostraps virtualenv inside a `venv` directory while the `.gitignore` file ignores `.venv`

fix: (minor) setup instructions

---

setup.cfg
tests/chains/test_tezos.py

Bumped pytezos to a version that supports verifying signatures
generated by Ed25519 keys. Added a test to avoid regressions.

Fix: Support Ed25519 Tezos keys

---

setup.cfg

Use the hash on aleph-pytezos:master instead of the PR branch
for Ed25519 support.

Fix: commit hash for pytezos

---

setup.cfg

The schema of Aleph messages is validated against aleph-message definitions since v0.3.3. The support for persistent VMs adds new fields that are not present in `aleph-message` version `0.1.20`, and an upgrade is necessary.

Internal: Persistent VM messages were rejected

---

src/aleph/web/controllers/messages.py
src/aleph/web/controllers/posts.py
tests/api/test_messages.py

The _id field no longer appears in the response of the messages
and posts endpoints.
Resolves #264.

[API] Remove MongoDB object ID from responses

---

setup.cfg
src/aleph/handlers/storage.py
src/aleph/schemas/pending_messages.py
tests/storage/test_store_message.py

Fixed a test case related to item hash validation. Fixed an error where some invalid STORE messages could still be stored in the database.

Chore: bump aleph-message for ItemHash type

---

src/aleph/commands.py
src/aleph/services/p2p/__init__.py
src/aleph/services/p2p/singleton.py
src/aleph/web/controllers/p2p.py

Problem: the P2P client object was stored in a singleton for use within API endpoints. Singleton objects can be complex to handle and introduce subtle bugs.
Solution: store the P2P client within the aiohttp application context.

Internal: store P2P client in aiohttp app context

---

src/aleph/chains/common.py
src/aleph/handlers/forget.py
src/aleph/handlers/storage.py
src/aleph/jobs/process_pending_messages.py
src/aleph/jobs/process_pending_txs.py
src/aleph/network.py
src/aleph/permissions.py
src/aleph/schemas/base_messages.py
src/aleph/schemas/message_content.py
src/aleph/schemas/pending_messages.py
src/aleph/schemas/validated_message.py
src/aleph/services/ipfs/pubsub.py
src/aleph/services/p2p/protocol.py
src/aleph/storage.py
tests/chains/test_common.py
tests/chains/test_confirmation.py
tests/chains/test_tezos.py
tests/conftest.py
tests/helpers/message_test_helpers.py
tests/message_processing/load_fixtures.py
tests/message_processing/test_perform_db_operations.py
tests/message_processing/test_process_pending_txs.py
tests/permissions/test_check_sender_authorization.py
tests/schemas/test_pending_messages.py
tests/schemas/test_validated_messages.py
tests/storage/forget/test_forget_message.py
tests/storage/forget/test_forget_multi_users.py
tests/storage/test_get_content.py
tests/storage/test_store_message.py
tests/test_network.py

Propagated the use of Pydantic message models to all the functions
related to message processing.
Extended the Pydantic message models by introducing a new
message class, `ValidatedBaseMessage`. This schema represents
fully-loaded messages, including their content field.
Split the message validation function, check_message, in two parts:
* `parse_message` checks that the message is semantically valid,
i.e. that all the required fields are present, are of the correct
type and have sensible values.
* `verify_signature` checks the signature of the message using
the public key of the sender.
We now call parse_message as early as possible in the process.
This allows to simplify hypotheses about the presence/absence
of specific fields and allows to simplify the codebase.
Improved the typing of …

[Messages] Use Pydantic message models everywhere

---

src/aleph/jobs/process_pending_messages.py

Problem: if an invalid message somehow managed to reach the pending message collection, the message would be retried indefinitely logging exceptions on each run.
Solution: drop invalid messages.

Fix: drop invalid pending messages

---

src/aleph/model/messages.py
src/aleph/web/__init__.py
src/aleph/web/controllers/posts.py
tests/api/conftest.py
tests/api/test_messages.py
tests/api/test_posts.py
tests/api/utils/__init__.py
tests/conftest.py

Problem: the "/api/v0/posts.json" endpoint returns a 500 error because of an invalid parameter being used in a function (an attempt to remove the MongoDB object ID from the endpoint).
Solution: remove the object ID directly in the aggregate query.
Added a simple test to verify that the endpoint is at least working a little bit.

Fix: general 500 error on posts endpoint

---

tests/api/conftest.py
tests/api/fixtures/fixture_aggregates.json
tests/api/test_aggregates.py

Problem: the /api/v0/aggregates/{address}.json endpoint was not tested enough.
Solution: add tests.

Internal: add unit tests for the aggregates endpoint

---

src/aleph/web/controllers/aggregates.py
src/aleph/web/controllers/utils.py
tests/api/test_aggregates.py

Use a Pydantic model instead of manual validation.

Internal: improve validation of the aggregates endpoint

---

deployment/migrations/scripts/0003-retrieve-confirmation-time.py
src/aleph/chains/common.py
src/aleph/chains/ethereum.py
src/aleph/chains/nuls2.py
src/aleph/chains/tx_context.py
src/aleph/jobs/process_pending_messages.py
src/aleph/jobs/process_pending_txs.py
src/aleph/schemas/message_confirmation.py
src/aleph/schemas/validated_message.py
tests/chains/test_confirmation.py
tests/message_processing/test_process_pending_txs.py
tests/schemas/test_validated_messages.py
tests/storage/test_store_message.py

Problem: a part of the information regarding on-chain confirmations
is dropped, thereby losing useful metadata for use in later processes.
Example: the time field of confirmations could be used to determine
when confirmations were received.
Solution: store the entire transaction context in the confirmations
array of messages. This means that two additional fields are now
preserved: the transaction block timestamp and the publisher.
As we need to re-fetch this data from chain data, a new migration
script resets the chain height to re-process all transactions.
We reset the confirmation status of all messages to unconfirmed
and deleted their confirmations array to let the node automatically
migrate to the new format.

Internal: store the full TX context in confirmations

---

src/aleph/web/controllers/messages.py
src/aleph/web/controllers/utils.py
tests/api/test_messages.py
tests/api/utils/__init__.py

Problem: the messages.json endpoint was too permissive, allowing users to specify invalid chains, message types, make incoherent pagination / time filtering, etc.
Solution: detect these cases and return a 422 error.
Replaced the custom validation code of the endpoint by a Pydantic model. Added tests for start/end date parameters and pagination.
Breaking changes:
* The "endDate" field is now considered as exclusive. Only messages with a time field strictly lower than the value will be returned, instead of a value lower or equal before.
* The endpoint now returns a 422 error instead of a 400 when incorrect parameters are passed.
Moreover, a 422 error code will now be returned in the following situations, where the previous implementation would simply return a 200:
* if an invalid/unknown …

Feature: return errors for invalid message API queries

---

src/aleph/web/controllers/messages.py

Problem: the message websocket could receive "startDate"/"endDate"
and pagination parameters.
Solution: use a slightly different Pydantic model for the websocket
to reject these parameters.

Fix: refuse time and pagination parameters for message WS

---

src/aleph/chains/common.py
src/aleph/chains/ethereum.py

Problem: if the chain data push operation fails, the associated file is not deleted from the node. As failures can occur repeatedly (ex: insufficient balance), such files end up taking an unreasonable amount of storage space.
Solution: delete the chain data file from local storage if the broadcast operation fails.
We do not delete the file from IPFS at the moment, as for IPFS only a few blocks are added on each failed push.

Fix: delete chain data files that could not be broadcast

---

src/aleph/web/controllers/messages.py
tests/api/test_messages.py

Problem: the time filters are ignored in the messages.json endpoint since #337.
Solution: reactivate the filtering.

Fix: reactivate message API time filters

---

src/aleph/web/controllers/messages.py
src/aleph/web/controllers/posts.py
src/aleph/web/controllers/utils.py

Problem: the posts.json endpoint is too permissive and allows users to specify invalid hashes, time filters, pagination, etc.
Solution: detect these cases and return a 422 error.
Replaced the validation code by a Pydantic model.
Breaking changes:
* The "endDate" field is now considered as exclusive.
Moreover, a 422 error code will now be returned in the following situations, where the previous implementation would simply return a 200:
* if an invalid item hash (=not a hexadecimal sha256, CIDv0 or CIDv1) is specified in the "hashes" or "contentHashes" field.
* if the "endDate" field is lower than the "startDate" field.
* if "endDate" or "startDate" are negative.
* if pagination parameters ("page" and "pagination") are negative.

Feature: return errors for invalid post API queries

---

src/aleph/web/controllers/messages.py
tests/api/test_messages.py

Problem: the new validation system did not parse the `refs` and `hashes` list parameters correctly.
Solution: apply the list validator to these fields as well.

Fix: parse refs and hashes fields correctly for messages API

---

deployment/scripts/run_aleph_ccn.sh

Problem: the CCN startup script calls wait-for-it on the IPFS daemon even if `ipfs.enabled` is set to false.
Solution: check `ipfs.enabled` and skip the check accordingly.

Fix: support disabling IPFS

---

setup.cfg
src/aleph/services/p2p/pubsub.py
src/aleph/web/controllers/p2p.py

Problem: the messages sent to the `pub_json` endpoint are forwarded to the network using P2P/IPFS pubsubs but are not actually processed on the node.
Solution: use the latest version of the P2P service client and use the new loopback feature.

Fix: process messages received from the REST API

---

src/aleph/chains/avalanche.py
src/aleph/chains/cosmos.py
src/aleph/chains/nuls.py
src/aleph/chains/nuls2.py
src/aleph/chains/solana.py
src/aleph/chains/substrate.py
src/aleph/chains/tezos.py
src/aleph/chains/tx_context.py
src/aleph/config.py
src/aleph/model/messages.py
src/aleph/schemas/base_messages.py
src/aleph/schemas/chains/tezos_indexer_response.py
tests/chains/test_cosmos.py
tests/chains/test_register.py
tests/chains/test_tezos.py

Problem: Users need a solution to pin content on Aleph automatically when minting NFTs on Tezos.
Solution: Add a sync worker to fetch messages from the Aleph sync smart contract on Tezos and transform them into valid Aleph messages.
Replaces #355 since that branch is on a fork.

Feature: Tezos message sync

---

setup.cfg
tests/chains/test_substrate.py

Chore: PyAleph can not validate signature coming from Polkadotjs provider.
Solution: update substrate-interface from `1.1.7` to `1.2.0`
The minimal version to fix this issue is the `1.2.0`.
https://github.com/polkascan/py-substrate-interface/releases/tag/v1.2.0
This update is required for the typescript SDK: https://github.com/aleph-im/aleph-sdk-ts/pull/108

Chore: Allow provider polkadot signature verification

---

deployment/samples/docker-compose/sample-config.yml

The p2p service failed to connect to the rest of the network using the configured peers. The default configuration of pyaleph is in Python code and cannot be read from the p2p-service.
Solution: override the default peers in the default configuration file as well.
Related: Fix the default values in the configuration of p2p-service in https://github.com/aleph-im/p2p-service/pull/42

Fix: Default peers of p2p-service did not work

---

deployment/migrations/versions/0010_8a5eaab15d40_address_stats_view.py
src/aleph/commands.py
src/aleph/db/accessors/messages.py
src/aleph/services/cache/materialized_views.py
src/aleph/web/controllers/accounts.py
tests/db/test_accounts.py

Problem: the response time of the stats endpoint is too slow because we perform a group by query on the whole message table every time.
Solution: go back to caching. We use a postgres materialized view to this purpose to make this cache available to other endpoints.

Fix: slow response times on addresses/stats.json

---

src/aleph/chains/indexer_reader.py

Problem: the chain name is hardcoded to Tezos.

Fix: use correct chain name in indexer messages

---

src/aleph/config.py

Problem: node operators complain that the log files for the different processes making up the node take up too much space.
Solution: reduce the maximum log file size to 50MB. As we rotate logs up to 6 times, this reduces the total maximum log size from 6GB to 300MB per process.

Fix: reduce total log files size

---

deployment/samples/docker-compose/docker-compose.yml
deployment/samples/docker-monitoring/docker-compose.yml
deployment/scripts/run_aleph_ccn.sh
deployment/scripts/run_aleph_ccn_api.sh
deployment/scripts/wait_for_services.sh
setup.cfg
src/aleph/api_entrypoint.py
src/aleph/commands.py
src/aleph/web/__init__.py
tests/conftest.py

Problem: Users experience latency issues with the CCN API. This is caused by some parts of the code being synchronous: inherently for filesystem accesses, by design for DB accesses.
Solution: run multiple API processes.
We now use gunicorn to spawn several API worker processes. The API is now spawned as an independent container to make it easier to configure.
The API port and number of workers can be configured by setting the following environment variables:
- `CCN_CONFIG_API_PORT`
- `CCN_CONFIG_API_NB_WORKERS`.

Feature: separate API process

---

src/aleph/services/ipfs/service.py

Problem: the POST /messages/ endpoint fails to publish on the IPFS pubsub because the payload is bytes instead of a string as expected by aioipfs. This originates from the shift to `orjson` which encodes JSON as bytes.
Solution: convert to string before publishing.

Fix: cannot publish message from the API to IPFS pubsub

---

deployment/scripts/run_aleph_ccn_api.sh

Increased the timeout to 5 minutes to allow expensive API calls.

Fix: increase gunicorn worker timeout

---

deployment/samples/docker-monitoring/docker-compose.yml

Revert a typo in the Prometheus network in the monitoring Docker Compose.

Fix: wrong network name for Prometheus

---

deployment/docker-build/aiohttp.diff
deployment/docker-build/pyaleph.dockerfile
setup.cfg

Problem: a bug in aiohttp causes an assertion error to appear in the logs whenever an HTTP connection is lost.
Solution: there is no mainline fix in aiohttp. It is not trivial to install a forked version of aiohttp, so the simplest solution for now is to apply the aiohttp patch directly.
Bumped aiohttp to 3.8.4 at the same time.

Fix: aiohttp assert exception on connection lost

---

deployment/migrations/versions/0016_77e68941d36c_fix_ipfs_files_size.py
src/aleph/api_entrypoint.py
src/aleph/chains/chaindata.py
src/aleph/chains/ethereum.py
src/aleph/chains/nuls2.py
src/aleph/handlers/content/store.py
src/aleph/services/ipfs/service.py
src/aleph/storage.py
src/aleph/web/controllers/ipfs.py
src/aleph/web/controllers/storage.py
src/aleph/web/controllers/utils.py
tests/api/test_storage.py

Four fixes:
* files uploaded with the add_file/add_json endpoints are not downloadable.
* /ipfs/add_file is broken.
* /ipfs/add_file returned the wrong size, and we store the wrong size for IPFS files above 1MB when processing STORE messages.
* Unrelated, but the test API server was unable to use the IPFS client, making the fixes above harder to test locally.

Fix: storage API bugs

---

src/aleph/chains/ethereum.py
src/aleph/db/accessors/messages.py

Problem: camel case functions were removed from the web3 library.
Solution: use the snake case variants.
In addition, fixed the query to get unconfirmed messages that was missing a join when the chain is specified.

Fix: make Ethereum sync compatible with web3 6.0

---

src/aleph/db/accessors/messages.py
tests/db/test_messages.py

Problem: trusted messages were included in the results of `get_unconfirmed_messages` when confirming messages on-chain.
Solution: remove trusted messages from the query.

Fix: ignore trusted messages for on-chain sync

---

src/aleph/db/accessors/posts.py
tests/api/test_posts.py
tests/db/test_posts.py

Problem: amended posts do not appear when filtering the results of `/api/v0/posts.json` with the `refs` query parameter.
Solution: do not take the `ref` of the amend into account as it will always be equal to the `item_hash` of the original post.

Fix: filter amended posts by ref on /api/v0/posts.json

---

src/aleph/db/accessors/messages.py
src/aleph/db/accessors/posts.py
tests/api/conftest.py
tests/api/test_list_messages.py
tests/api/test_posts.py

Problems:
* the `tags` filter in /messages.json is not additive and filters out
messages that don't match all the specified tags, instead of returning
messages that have at least one matching tag.
* filtering posts by tags filters out all results.
Solution: fix the SQL queries, the filter was comparing the specified
tags against the post tags as strings instead of checking for
inclusion. We now use the '?|' operator to check if the message/post
tags match at least one of the specified tags.

Fix: filtering by tags

---

src/aleph/web/controllers/p2p.py

Problem: 5 seconds is a bit short.
Solution: increase to 30 seconds.

Fix: increase POST /messages sync timeout

---

src/aleph/api_entrypoint.py
src/aleph/web/controllers/app_state_getters.py
src/aleph/web/controllers/messages.py
src/aleph/web/controllers/p2p.py
src/aleph/web/controllers/utils.py

Problem: opening more than ~2000 message websockets hits the channel limit of RabbitMQ and resets the connection.
Solution: create one channel per API process, as they are long-lived and should not be created for each operation according to the doc.

Fix: support very large number of open websockets

---

setup.cfg
src/aleph/web/controllers/messages.py
src/aleph/web/controllers/p2p.py

* Avoid acknowledgement issues in message WS
* Properly terminate requests to the message WS.

Fix: websocket issues

---

deployment/docker-build/docker-compose.yml
deployment/samples/docker-compose/docker-compose.yml
deployment/samples/docker-monitoring/docker-compose.yml

Problem: some SQL queries end up requiring more than the (limited) amount of shared memory allocated to Docker containers by default.
Solution: increase it to 2GB.

Fix: increase shared memory size for PostgreSQL container

---

src/aleph/web/controllers/messages.py
src/aleph/web/controllers/p2p.py
src/aleph/web/controllers/utils.py

Problem: upon closing, the message websocket may attempt to close the RabbitMQ channel. This appears to be caused by the handling of `CancellationError` in the `close()` method of the queue iterator.
Solution: replace the `iterator` implementation with a simpler `consume` + callback implementation. This guarantees that the secondary task will never attempt to close the channel. Replace task cancellation by a call to `queue.cancel()` as aiormq handles cancellation exceptions by closing the channel.

Fix: avoid channel closed exception in message websocket

---

src/aleph/handlers/message_handler.py
src/aleph/jobs/job_utils.py
src/aleph/jobs/process_pending_messages.py
src/aleph/types/message_processing_result.py
tests/helpers/message_test_helpers.py
tests/message_processing/test_process_aggregates.py
tests/message_processing/test_process_forgets.py

Problem: websocket users report messages appearing twice, as they are received on both the P2P and IPFS pubsub topics.
Solution: ignore confirmations. The scaffolding was already in place, we just need to return a `ProcessedMessage` instead of a raw `MessageDb` from `MessageHandler.process()`.

Fix: do not send confirmations to message websocket

---

src/aleph/api_entrypoint.py
src/aleph/web/controllers/app_state_getters.py
src/aleph/web/controllers/messages.py

Problem: the message websocket appears to close the channel in some situations. We want to avoid a contagion to the other endpoints using the MQ.
Solution: use a separate channel. The WS issue will not propagate to other channels.

Internal: use a separate MQ channel for websockets

---

src/aleph/web/controllers/app_state_getters.py
src/aleph/web/controllers/messages.py
src/aleph/web/controllers/p2p.py

Problem: the MQ channels can close for a variety of issues. Once closed, the channel cannot be used anymore.
Solution: detect if the channel is closed and reopen it if needed.

Fix: reopen the API MQ channels if they are closed

---

deployment/migrations/versions/0017_f9fa39b6bdef_vm_instances.py
setup.cfg
src/aleph/db/models/vms.py
src/aleph/handlers/content/vm.py
tests/message_processing/test_process_instances.py

Adaptations to the latest update of aleph-message.

Fix: remove cloud-init support and add authorized keys

---

src/aleph/schemas/api/messages.py
tests/api/test_list_messages.py

Problem: instance messages API schemas were not implemented.

Fix: 500 error when listing instance messages

---

src/aleph/jobs/process_pending_messages.py
src/aleph/schemas/api/messages.py
src/aleph/types/message_processing_result.py
src/aleph/web/controllers/messages.py
tests/api/test_get_message.py

Problem: the websocket uses the DB to apply filters to processed messages to determine whether they must be sent on the websocket. This leads to an exhaustion of DB connections when many websockets are open with the same filters.
Solution: send the full message on the RabbitMQ topic and apply filters in Python instead of using a DB query.

Fix: no DB calls in message websocket

---

src/aleph/toolkit/shield.py
src/aleph/web/controllers/messages.py
src/aleph/web/controllers/p2p.py

Problem: resources are not cleaned up properly when the message websocket handler is cancelled. This is because aiohttp appears to raise a CancellationError.
Solution: use `asyncio.shield()` on the whole handler. Added a decorator to avoid splitting the implementation of shielded functions.
Protected the POST /messages endpoint as well as it also uses a message queue.
fix

Fix: prevent cancellation of the message websocket

---

src/aleph/chains/solana.py
src/aleph/schemas/base_messages.py
tests/chains/test_solana.py

Problem: invalid Solana signatures are logged as exceptions, even if the error is actually handled properly.
Solution: change log level to warning.

Fix: no exception log on Solana signature error

---

src/aleph/schemas/pending_messages.py
tests/message_processing/test_process_forgets.py

Problem: the instance message type was missing from a dictionary.
Solution: add it.

Fix: 500 error when submitting instance message

---

src/aleph/handlers/content/store.py

Problem: the condition to pin the files is inverted.

Fix: large IPFS files were not pinned

---

src/aleph/web/controllers/messages.py

Problem: we checked refs as a message-level fields instead of `content.ref`.

Fix: refs were not filtered properly in message websocket

---

deployment/migrations/versions/0018_7bcb8e5fe186_fix_vm_cost_view.py
tests/api/test_balance.py
tests/db/test_cost.py

Problem:
- View was using Mb instead of MiB

Fix: cost_view

---

src/aleph/web/controllers/p2p.py

Problem: Posting to /messages without a body causes a 500.
Solution: catch the error and raise a 422 instead.

Fix: return 422 on POST /messages if body is not JSON

---

src/aleph/chains/indexer_reader.py

Problem: indexer queries fail because of a breaking change. The blockchain parameter is now a literal string instead of an enum value, requiring additional quotes.
Solution: add quotes around the blockchain parameter value.

Fix: 400 error on indexer queries

---

deployment/migrations/versions/0017_f9fa39b6bdef_vm_instances.py
src/aleph/types/message_status.py

Problem: nodes that do not support instances yet will have marked instance messages as rejected.
Solution: use the migration script to put these messages back in the pending queue and reprocess them once the node restarts.

Fix: reprocess failed instance messages in migration script

---

deployment/migrations/versions/0018_7bcb8e5fe186_fix_vm_cost_view.py
src/aleph/handlers/content/vm.py
src/aleph/services/cost.py
tests/message_processing/test_process_instances.py
tests/message_processing/test_process_programs.py

Based on : https://github.com/aleph-im/pyaleph/pull/462
Solutions:
- Add check of the balance for VM persistent
- Fix View who did not show Persistent VM

Feature : Balance Check persistent VM

---

src/aleph/__init__.py
src/aleph/api_entrypoint.py
src/aleph/schemas/pending_messages.py
src/aleph/storage.py
src/aleph/web/controllers/app_state_getters.py
src/aleph/web/controllers/ipfs.py
src/aleph/web/controllers/p2p.py
src/aleph/web/controllers/storage.py
src/aleph/web/controllers/utils.py
tests/api/test_p2p.py
tests/api/test_storage.py

Problem: file upload is performed in two steps, one to push the file and one to push the associated STORE message.
Solution: improve `/api/v0/storage/add_file` to allow the user to send a STORE message along with his file, making upload an atomic operation.

Feature: authenticated file upload

---

src/aleph/db/accessors/aggregates.py
src/aleph/web/controllers/aggregates.py
tests/api/test_aggregates.py
tests/message_processing/conftest.py

Problem :
To avoid fetching all the messages to find the creation/modification time of a specific aggregate entry it will be useful to have this info directly in the aggregate message
Solution:
Update '/api/v0/aggregates' Endpoint
param : 
- with_info: bool default : False 
From :
```
{
"address": "0xa1B3bb7d2332383D96b7796B908fB7f7F3c2Be10",
"data": {
"key1": ...,
"key2": ...,
}
}
```
To:
```
{
"address": "0xa1B3bb7d2332383D96b7796B908fB7f7F3c2Be10",
"data": {
"key1": ...,
"key2": ...,
}
"info": {
"key1": {
"created": ...,
"last_updated": ...,
"original_item_hash": ...,
"last_update_item_hash: ...,
},
"key2": ...
}
}
```
Fixes #470.

Feature: modification and creation date in the aggregate messages

---

src/aleph/web/controllers/utils.py

Problem: The secure upload functionality does not provide the `message_dict` argument to the `broadcast_and_process_message` utility function. This causes a 500 error.
Solution: Make the parameter default to None. Document `broadcast_and_process_message`.

Fix: missing parameter for broadcast_and_process

---

src/aleph/chains/bsc.py
src/aleph/chains/chain_data_service.py
src/aleph/chains/connector.py
src/aleph/chains/ethereum.py
src/aleph/chains/indexer_reader.py
src/aleph/chains/nuls2.py
src/aleph/chains/tezos.py
src/aleph/jobs/process_pending_txs.py
src/aleph/schemas/chains/sync_events.py
src/aleph/storage.py
tests/chains/test_chain_data_service.py
tests/message_processing/test_process_pending_txs.py

Problem: a few todos are still open on the chain data service.
Solution: improve and rename the `get_chaindata` method. The new `prepare_sync_event_payload` method now always returns an off-chain sync event (on-chain sync events never occur anyway). It also returns the result as a Pydantic model for more flexibility. Serialization is left upon the caller. We now use a Pydantic model to translate `MessageDb` objects in the correct format.

Internal: improve chain data service

---

src/aleph/chains/chain_service.py
src/aleph/commands.py
src/aleph/config.py
src/aleph/services/ipfs/common.py

Added documentation for the `aleph.config` module and removed unused configuration options.

Doc: configuration module

---

src/aleph/handlers/message_handler.py
tests/chains/test_confirmation.py
tests/message_processing/test_process_aggregates.py
tests/message_processing/test_process_stores.py

Problem: the `fetch_and_process_one_message_db` method of the message handler is only used in tests and is only a light wrapper around `process()`.
Solution: remove it and replace it by calls to `MessageHandler.process()`.

Internal: remove test-only method of MessageHandler

---

src/aleph/handlers/message_handler.py
src/aleph/jobs/fetch_pending_messages.py
src/aleph/jobs/process_pending_messages.py
src/aleph/jobs/process_pending_txs.py
src/aleph/network.py
src/aleph/services/ipfs/pubsub.py
src/aleph/services/p2p/protocol.py
tests/api/conftest.py
tests/chains/test_confirmation.py
tests/message_processing/conftest.py
tests/message_processing/test_process_aggregates.py
tests/message_processing/test_process_pending_txs.py
tests/message_processing/test_process_stores.py
tests/test_network.py

Problem: the message handler implements two functionalities:
1. validate + add pending messages to the DB
2. process pending messages.
The dependencies for each task are starting to diverge so it makes sense to split the message handler.
Solution: put all common functionalities in the `BaseMessageHandler` base class and add a new `MessagePublisher` class that is in charge of validating and adding pending messages to the DB.

Internal: split message handler

---

src/aleph/chains/bsc.py
src/aleph/chains/chain_data_service.py
src/aleph/chains/connector.py
src/aleph/chains/ethereum.py
src/aleph/chains/indexer_reader.py
src/aleph/chains/nuls2.py
src/aleph/chains/tezos.py
src/aleph/commands.py
src/aleph/config.py
src/aleph/db/accessors/pending_txs.py
src/aleph/jobs/job_utils.py
src/aleph/jobs/process_pending_txs.py
tests/message_processing/test_process_pending_txs.py

Problem: the pending TX processor uses a polling loop to determine which transactions must be processed. This leads to some latency when adding a new transaction when there is no currently pending transaction as the task sleeps while waiting for new transactions.
Solution: make the TX processor event-based by using a RabbitMQ exchange
+ message queue. Upon receiving a new transaction from on-chain, we now publish a RabbitMQ message containing the hash of the transaction. The processor can then find the transaction in the DB.
We still store an entry in the pending TXs table for monitoring purposes.

Internal: TX processing is now event-based

---

src/aleph/api_entrypoint.py
src/aleph/commands.py
src/aleph/jobs/fetch_pending_messages.py
src/aleph/jobs/process_pending_messages.py
src/aleph/jobs/process_pending_txs.py
src/aleph/services/cache/node_cache.py
tests/conftest.py

Problem: a warning occurs in the tests because of an improper cleanup of the Redis client object.
Solution: make the NodeCache class an asynchronous context manager and make it clean up after itself.

Fix: warning on failure to close node cache properly

---

deployment/docker-build/docker-compose.yml
deployment/samples/docker-compose/docker-compose.yml
deployment/samples/docker-monitoring/docker-compose.yml

The upgrade seems to create issues when syncing a new node. This needs to be investigated for a later release.

Revert: downgrade Kubo from 0.23.0 to 0.15.0

---

deployment/migrations/versions/0021_e682fc8f9506_fix_vm_costs_view.py

Broke because merging #527 and #528 without rebasing alembic migration files

Fix: Revise latest alembic migration to use previous, latest head

---

src/aleph/db/accessors/messages.py
src/aleph/web/controllers/messages.py

Filter and sort objects (messages, posts, etc) by confirmation block ID #445

---

setup.cfg
src/aleph/handlers/content/vm.py

Problem: Checking the balance on Pay-as-you-go payment method don't allow the message to be processed.
Solution: Exclude stream payment method on balance check system.

Exclude `stream` payment system from balance check

---

setup.cfg
src/aleph/db/accessors/messages.py
src/aleph/handlers/content/vm.py
src/aleph/services/cost.py
src/aleph/web/controllers/prices.py
src/aleph/web/controllers/routes.py
tests/schemas/test_pending_messages.py

Problem: We are unable to get the required tokens or flow for an instance or program VM.
Solution: Create a price API to request it just passing the message item hash.

Implement price API

---

src/aleph/db/accessors/metrics.py
tests/api/test_new_metric.py

This causes a lot of data to be returned in the case of old nodes and is usually unnecessary.
Solution: Default to limiting the query to the last 2 weeks of data, or to 2 weeks before the specified date of last data.
This also renames `start_date -> start_timestamp` and `end_date -> end_timestamp` to prevent confusion since these fields are expected to be timestamps and note datetime or ISO 8601.
Related to https://github.com/aleph-im/pyaleph/pull/528

Fix: All node metrics were returned by default

---

src/aleph/services/ipfs/service.py
src/aleph/toolkit/monitoring.py

Two small improvements in error handling and reporting
- Fix: Sentry AsyncioIntegration was missing
- Fix: Response was processed even in case of error status code

Improve error handling

---

src/aleph/web/controllers/messages.py
src/aleph/web/controllers/posts.py
tests/api/test_list_messages.py

- Linked to [issue 95 on SDK](https://github.com/aleph-im/aleph-sdk-python/issues/95) -> Solved here: [PR](https://github.com/aleph-im/aleph-sdk-python/pull/104)
- No sorting when queries request it, even after changing SDK codebase: 
- Added missing aliases on BaseMessageQueryParams & PostQueryParams
@hoh

Fix sortBy/sortOrder on Message/Post queries

---

src/aleph/chains/chain_data_service.py
src/aleph/services/ipfs/service.py
src/aleph/storage.py
src/aleph/web/controllers/ipfs.py
tests/api/test_storage.py
tests/chains/test_chain_data_service.py

The Chain writer task for Chain.ETH failed with the following stacktrace:
```
aleph-pyaleph-1 | 2024-01-29 14:09:32 [ERROR] aleph.chains.connector: Chain writer task for Chain.ETH failed, relaunching in 10 seconds.
aleph-pyaleph-1 | Traceback (most recent call last):
aleph-pyaleph-1 |   File "/opt/pyaleph/src/aleph/chains/connector.py", line 63, in chain_writer_task
aleph-pyaleph-1 |     await connector.packer(config)
aleph-pyaleph-1 |   File "/opt/pyaleph/src/aleph/chains/ethereum.py", line 351, in packer
aleph-pyaleph-1 |     await self.chain_data_service.prepare_sync_event_payload(
aleph-pyaleph-1 |   File "/opt/pyaleph/src/aleph/chains/chain_data_service.py", line 75, in prepare_sync_event_payload
aleph-pyaleph-1 |     ipfs_cid = await self.storage_service.add_file(
aleph-pyaleph-1 | …
```

Fix: Chain writer failed due to `TypeError`

---

.github/workflows/nix-ci.yml
README.md
shell.nix

Solution: Provide a `shell.nix` file so developers can just run `nix-shell` to start temporary PostgreSQL and Redis servers.
The exit signal of the shell is `trap`-ed in order to automatically stop the services on exit.
https://github.com/aleph-im/pyaleph/assets/404665/bb013aec-ca54-4aa7-afad-2febbe1f0f09

Allow developers to use nix-shell to get started

---

src/aleph/web/controllers/messages.py
src/aleph/web/controllers/posts.py
tests/api/test_list_messages.py

@see https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.populate_by_name
related to #555

Fix Pydantic alias issue

---

src/aleph/services/cost.py
tests/services/test_cost_service.py

Fix: Required flow price calculation was failing, now it is fixed also with tests.

Solve Flow pricing calculation issues

---

setup.cfg
src/aleph/web/controllers/storage.py
tests/api/test_storage.py

[Issue](https://github.com/aleph-im/pyaleph/issues/564)
Issue Description:
The current file upload endpoint reads the entire file before checking if it exceeds the maximum allowed size. The size limits are 25 MB for unauthenticated uploads (MAX_UNAUTHENTICATED_UPLOAD_FILE_SIZE) and 1000 MB for authenticated uploads (MAX_UPLOAD_FILE_SIZE).
Proposed Solutions:
- Read the file in chunks and check if the size exceeds the maximum allowed size.
- Use a temporary file to handle the data, which helps avoid using too much memory.

Fix: Upload Endpoints

---

README.md

There are still a lot of other MongoDB references still present that we probably want to get ride off but they are in the documentation and I think this need a whole rewrite?
```
❯ rg -i mongo
CHANGELOG.rst
135:- Decommissioned the support for RocksDB. The only supported storage engine is now MongoDB.
deployment/samples/docker-monitoring/sample-config.yml
20:mongodb:
21:  uri: "mongodb://mongodb:27017"
docs/figures/architecture-stack.pdf
679:(MongoDB) Tj
docs/figures/PyAleph architecture.graphml
487:						<y:Label.Text>MongoDB</y:Label.Text>
docs/guides/install.rst
132:Download the Docker Compose file that defines how to run PyAleph, MongoDB and IPFS together.
176:    * - nfuser_mongodb_1
177:      - docker-entrypoint.sh mongo ...
212:Check PyAleph data via MongoDB
215:MongoDB message …
```

doc(README): we don't use mongodb anymore

---

.github/workflows/nix-ci.yml
deployment/migrations/env.py
shell.nix
src/aleph/commands.py
tests/conftest.py

List of modifications and improvements: 
* add pkgs.glibcLocales because otherwise locales aren't handles and postgresql fails
* ensure that we have at least a default config.yml otherwise tests won't launch
* display information information at the end of the output log of nix-shell and in bold otherwise it's hidden in the logs
* wrap shellHooks in `set -eu` otherwise you can have error, nix won't complain and you'll end up in a broken nix-shell not understanding why
* make tests fixtures take into account config.yml otherwise it's simply ignored and only the default are used
* launch postgresql on port 5434 because users can have postgresql on 5432 (or even 5433) and nix-shell will just fails 
* and remove an unused import

a lot of fixes and improvement for running local tests using nix-shell because it was just broken

---

src/aleph/web/controllers/prices.py

[Issue](https://github.com/aleph-im/pyaleph/issues/576)
Problem:
When a volume is not found, it's returning error 500 instead of returning a web response 
Solution:
Catch runtime error and return the error as web error

Fix: Handle no volume found instead of error 500

---

.gitignore
src/aleph/db/connection.py
tests/conftest.py

Before that, it was only possible to connect pyaleph to postgresql using an ip/domain and only with a password.
I've also fix a bug in the tests that was overwriting some configuration.
This PR has been extracted from #574 
This PR can be "rebase and merge" since all commits are standalone.

Allow to connect postgresql in a passwordless mode and with a unix socket

---

deployment/docker-build/README.md
deployment/samples/docker-monitoring/sample-config.yml
docs/guides/install.rst
tests/api/test_list_messages.py

We still have reference to MongoDB here which is not that great and professional https://pyaleph.readthedocs.io/en/latest/guides/install.html since it's linked here https://account.aleph.im/earn/ccn/

doc: remove references to MongoDB

---

shell.nix

Using nix-shell with the latest version of Nixpkgs raised the following
error:
```
bash: pop_var_context: head of shell_variables not a function context
```
Changing the order of the instructions fixed this.

Fix: nix-shell raised 'pop_var_context'

---

src/aleph/storage.py
src/aleph/toolkit/json.py
tests/toolkit/test_json.py

Problem: On large integer values `orjson` library shows an `TypeError:Integer exceeds 64-bit range` error.
In case that `orjson` cannot handle the issue and raise a `TypeError` issue, we handle it running a normal `json.XXX` method.
Try to run queries with large int numbers.

Solve large int errors

---

tests/toolkit/test_json.py

Fix: Add a test for large ints to ensure don't raises a TypeError
Added a test case ensuring that large ints doesn't break the json load and dump
Execute the test suite

Added large ints test case

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/code-quality.yml
.github/workflows/nix-ci.yml
.github/workflows/pytest.yml
.github/workflows/test-keygen.yml
.readthedocs.yml
deployment/docker-build/config.yml
deployment/docker-build/docker-compose.yml
deployment/samples/docker-compose/docker-compose.yml
deployment/samples/docker-compose/sample-config.yml
deployment/samples/docker-monitoring/docker-compose.yml
deployment/samples/docker-monitoring/grafana/dashboard.yaml
deployment/samples/docker-monitoring/grafana/prometheus.yaml
deployment/samples/docker-monitoring/prometheus.yml
deployment/samples/docker-monitoring/sample-config.yml
pyproject.toml

This is to match https://github.com/aleph-im/aleph-vm/pull/705
I've also relaunch yamlfix on the yaml to enforce those new options.
ALEPH-204

add missing configurations options for yamlfix

---

src/aleph/web/controllers/messages.py
src/aleph/web/controllers/routes.py
tests/api/test_get_message.py

Related tickets : [ALEPH-253](https://aleph-im.atlassian.net/jira/software/c/projects/ALEPH/boards/2?selectedIssue=ALEPH-253)
Implement a `/api/v0/messages/{item_hash}/content` route path that return directly the `content.content` fields from POST messages.
Check that the `/content` path exists and returns the content itself for POST messages, like : https://api3.aleph.im/api/v0/messages/fee8795bb8ac594eeb9624ce169bd5efc52842470da3c95dbc2d3291c3ad8643/content

Implement messages `content` path

---

pyproject.toml
src/aleph/chains/ethereum.py
src/aleph/chains/evm.py
src/aleph/chains/signature_verifier.py
tests/chains/test_evm.py

Related Jira ticket : [ALEPH-279](https://aleph-im.atlassian.net/jira/software/c/projects/ALEPH/boards/2?selectedIssue=ALEPH-279)
Changed the `aleph_message` dependency to use the last version with new EVM definitions.
Also created a class called `EVMVerifier` that gets the abstraction about how to verify EVM chains, and extend the `EthereumVerifier` to use it.
Try to send messages using that new EVM chains on the `CHAIN` field of the message, like `"CHAIN": "POL"`.
This [PR](https://github.com/aleph-im/aleph-message/pull/116) should be merged before at the deployment time.

Implement new EVM chains

---

src/aleph/services/p2p/protocol.py

With the patch done one version `0.5.7` we added a call to ACK the messages already handled before, but indeed it was already done by the `receive_messages()` method, so we end with these kind of errors:
```
2024-11-12 13:55:03 [ERROR] aleph.services.p2p.protocol: Exception in pubsub, reconnecting.
Traceback (most recent call last):
File "/opt/pyaleph/src/aleph/services/p2p/protocol.py", line 25, in incoming_channel
async for message in p2p_client.receive_messages(topic):
File "/opt/venv/lib/python3.12/site-packages/aleph_p2p_client/client.py", line 158, in receive_messages
async for message in self.mq_client.receive_messages(topic):
File "/opt/venv/lib/python3.12/site-packages/aleph_p2p_client/client.py", line 73, in receive_messages
await message.ack()
File …
```

Remove double `ack()` method call

---

src/aleph/schemas/api/messages.py
src/aleph/web/controllers/messages.py
src/aleph/web/controllers/routes.py

In certain scenarios, we need to determine the status of a message without retrieving all its contents, as this can consume significant memory and time, particularly when the message is large. This PR introduces a fast endpoint that returns only the status field and the reception time, providing the necessary information without unnecessarily loading the system.
- [ x] Is my code clear enough and well documented
- [ x] Are my files well typed
Add new endpoint to retreive the status info of a specific message
https://api.twentysix.testnet.network/api/v0/messages/ae2ae5ee6805c6ba91e1991b6079823a8999254f40837c45248c533624c49527/status
```json
{
"status": "processed",
"reception_time": "2024-11-20T15:13:07.404063+00:00"
}
```

Feature: Add new endpoint to retreive message status

---

src/aleph/db/accessors/balances.py
src/aleph/schemas/api/accounts.py
src/aleph/web/controllers/accounts.py
src/aleph/web/controllers/routes.py
tests/api/test_balance.py
tests/conftest.py

With new chain on aleph, as a user i can't get details of my balance.
The goal of the PR is to allow user filter balance base on chain and get the details.
This PR also introduce an new endpoint : `/api/v0/balances`
Related Clickup or Jira tickets : ALEPH-232
The /balances do same things as before but
This PR add 2 things
- A new field `details` exemple : `"details": {"AVAX": 447.1290583984875, "ETH": 
4002.070110401869}`
```
http://localhost:4024/api/v0/addresses/0xd463495a6FEaC9921FD0C3a595B81E7B2C02B57d/balance
{"address": "0xd463495a6FEaC9921FD0C3a595B81E7B2C02B57d", "balance": 4784.379935463618, "details": {"AVAX": 447.1290583984875, "BASE": 335.1807666632614, "ETH": 4002.070110401869}, "locked_amount": 0}
```
- A new filter `chain` takings a Chain like (ETH / AVAX / BASE)
``` …
```

Feature: details and chain filter on balance endpoint

---

src/aleph/db/accessors/messages.py
src/aleph/services/p2p/protocol.py

Query like `http://0.0.0.0:4024/api/v0/messages.json?msgType=POST&tags=mainnet&contentTypes=balances-update&pagination=50&sort_order=1&start_block=21135862&addresses=0xa1B3bb7d2332383D96b7796B908fB7f7F3c2Be10` was broken and generating a 500 error
Related Clickup or Jira tickets : ALEPH-302
So, basically until [this commit](https://github.com/aleph-im/pyaleph/commit/eb3b65369c6daea23616d90e038b02caa837e151) the `start_block/end_block` part of the code was never reached and was not working (except if you call the html query params `StartBlock`)
- first, a select query tried to access the `height` attribute on the table `message_confirmations` that doesn't have any height
- so using a join we grab the transaction `height` value 
- add it to the `GROUP BY`
- then we fix a priority operator …

Aleph-302: fix messages.json start_block and end_block params

---

pyproject.toml
src/aleph/web/controllers/messages.py

If an hash is not valid it's would return a error 500 instead of returning Bad Request.
Related Clickup or Jira tickets : ALEPH-110
Add try catch on ItemHash().
```
http://localhost:4024/api/v0/messages/{wrong_itemhash}
http://localhost:4024/api/v0/messages/{wrong_itemhash}/content
http://localhost:4024/api/v0/messages/{wrong_itemhash}/status
```

Fix: UnknownHashError in web.controllers.messages

---

pyproject.toml
src/aleph/web/controllers/posts.py

The types parameters for queries on /posts.json was not taken into account because it was badly named.
Related Clickup or Jira tickets : ALEPH-301
Just correctly name it.
Simply do a query on posts.json with the `types[]=...` query parameters like so:
```
curl 'http://localhost:4024/api/v0/posts.json?types[]=corechan-operation' | python -m json.tool | grep '"type":'
```

fix(api): correctly name types paramters of /posts.json

---

deployment/migrations/versions/0026_d3bba5c2bfa0_fix_join_exclude_vm_without_volume.py
src/aleph/handlers/content/store.py
tests/message_processing/test_process_instances.py

Related Clickup or Jira tickets : ALEPH-290
The `vm_costs_view` gets data from the `vms` table and joins it with volume data. The issue is with two `JOIN` statements:
1. **File Volumes (`file_volumes_size`)**  
If a VM doesn't have any file volumes, it gets excluded.
2. **Other Volumes (`other_volumes_size`)**  
If a VM doesn't have any other volumes, it also gets excluded.
This means VMs with only a `rootfs` (no extra volumes) won't show up in the results.
Change both `JOIN`s to `LEFT JOIN`s. This will include all VMs, even if they don’t have additional volumes.  
- [] Documentation has been included (for new feature)
This update addresses an issue where VMs without additional volumes (only `rootfs`) were being excluded from the results in the `vm_costs_view`. The changes ensure that all …

Fix: Vm cost view

---

src/aleph/chains/ethereum.py
src/aleph/config.py

This PR solves a timeout problem on some Ethereum RPCs, as the default timeout is set to 30s by the web3 client,
this PR allows the node operator to configure the timeout according to the rpc and network parameters.

config: Add a timeout option for the ethereum client

---

src/aleph/toolkit/libp2p_stubs/peer/id.py

This PR resolves a dependency conflict caused by two libraries, pymultihash and py-multihash, both of which provide a module named multihash. The conflict arises because:
pymultihash is required by pyaleph and is imported as multihash.
py-multihash is now required by aioipfs.
This pull request includes updates to the `src/aleph/toolkit/libp2p_stubs/peer/id.py` file to improve compatibility with the `multihash` library. The changes mainly involve updating import statements and method calls to reflect the latest structure of the `multihash` library.
Updates to `multihash` library usage:
* Updated import statements to include `multihash.funcs` for better organization and clarity.
* Changed `multihash.FuncReg.register` to `multihash.funcs.FuncReg.register` in the `update` method to align with …

Fix: import multihash (caused by aioipfs)

---

deployment/samples/docker-compose/docker-compose.yml
docs/conf.py
pyproject.toml
src/aleph/services/p2p/protocol.py

Solve issue with P2P huge amount of messages.
Updated p2p protocol to use the patched version of the p2p python client library and to avoid waiting 2 seconds everytime that the consumer fails.
Check the logs to see that doesn't appear any weird error.

Solve double processed P2P messages

---

deployment/migrations/versions/0027_bafd49315934_add_pending_messages_origin.py
src/aleph/db/models/pending_messages.py
src/aleph/handlers/message_handler.py
src/aleph/jobs/process_pending_messages.py
src/aleph/jobs/process_pending_txs.py
src/aleph/services/p2p/protocol.py
src/aleph/types/message_processing_result.py
src/aleph/types/message_status.py

This PR should solve P2P issue, over the network
Related Clickup or Jira tickets : ALEPH-XXX
This pull request introduces the `origin` field to the `pending_messages` table and updates relevant parts of the codebase to handle this new field. The changes ensure that the origin of each pending message is tracked and processed appropriately.
* Added a new column `origin` to the `pending_messages` table with a default value of "p2p".
* Imported `MessageOrigin` in `src/aleph/db/models/pending_messages.py` and added the `origin` field to the `PendingMessageDb` class. [[1]](diffhunk://#diff-e12fc9f12f46e0b67430c16317a11205c69eb2ae86b1934ffdda872383930cc4R23) [[2]](diffhunk://#diff-e12fc9f12f46e0b67430c16317a11205c69eb2ae86b1934ffdda872383930cc4R69)
* Updated the `from_obj` method in …

Fix: add origin pending message field

---

deployment/migrations/versions/0028_edb195b0ed62_fix_add_unique_constraint_on_pending_.py
pyproject.toml
src/aleph/db/models/pending_messages.py
src/aleph/handlers/message_handler.py
src/aleph/services/p2p/protocol.py
tests/message_processing/fixtures/test-data-pending-messaging.json
tests/message_processing/load_fixtures.py
tests/message_processing/test_process_pending_messages.py

Even though we use a memory cache, there was a risk of receiving the same pending message twice if the system crashed and reprocessed the message. We now ensure that this is no longer possible
Related Clickup or Jira tickets : ALEPH-NONE
This pull request includes changes to add a unique constraint on the `pending_messages` table to ensure data integrity. The changes involve creating a new database migration and updating the SQLAlchemy model for `pending_messages`.
Database migration:
* [`deployment/migrations/versions/0028_edb195b0ed62_fix_add_unique_constraint_on_pending_.py`](diffhunk://#diff-2661d66c0db80abdc821dc2903b8c8fb33112918bedc28b7bdb8a5f0d68126aeR1-R24): Added a new migration script to create a unique constraint on the `pending_messages` table for the columns `sender`, …

Fix: Pending message miss unique constraint

---

deployment/migrations/versions/0029_46f7e55ff55c_fix_uniqueconstraint_should_have_sender_.py
src/aleph/db/models/pending_messages.py

Fix unique constraint `uq_pending_message`,
There is now constraints on:
`sender`
`item_hash`
`signature`

Fix: pending_messages constraints 

---

src/aleph/handlers/message_handler.py
tests/message_processing/test_process_pending_messages.py

Fix: Instead to raise an integrity issue and try to add the message, check before if exists on the database and return the already existing

Solve integrity error logs on Postgresql

---

deployment/migrations/versions/0030_d8e9852e5775_fix_compute_message_status_on_vm_cost_.py

Vm_cost_view needed a join with message_status to avoid having a forgotten vms taking into account on `locked_ammount`
Related Clickup or Jira tickets : ALEPH-None
This pull request includes a significant update to the `vm_costs_view` in the database schema to include the `message_status` field. This change ensures that only VMs with a processed status are considered in the view.
Database Schema Update:
* [`deployment/migrations/versions/0030_d8e9852e5775_fix_compute_message_status_on_vm_cost_.py`](diffhunk://#diff-ada03adbdb04005ff99c78d0a8fa1449bbf17d1e46dd92e34d0bd13874ab7c3dR1-R165): Added a new migration script to update the `vm_costs_view` to include the `message_status` field and filter VMs based on the status 'processed'. This ensures that only processed VMs are included in the …

Fix: vm_cost_views missing join with status

---

deployment/migrations/versions/0030_9e600f404aa1_add_new_error_code_on_db.py
src/aleph/db/accessors/vms.py
src/aleph/handlers/content/forget.py
src/aleph/handlers/content/store.py
src/aleph/types/message_status.py
tests/message_processing/test_process_forgets.py

Fix: Prevent a store message forget to be executed if the file is already used on a VM.
Related Clickup or Jira tickets : ALEPH-XXX
Fix: Prevent a store message forget to be executed if the file is already used on a VM.
Try to forget a volume that is used by a program or an instance. The forget should be blocked and the API should answer an error.

Prevent delete volumes used by VMs

---

src/aleph/services/ipfs/pubsub.py
src/aleph/services/ipfs/service.py

Fix: Solved program crashing and restart if IPFS subscription raise an issue. Now it handles and log the issue without crashing.
Related Clickup or Jira tickets : [ALEPH-359](https://aleph-im.atlassian.net/browse/ALEPH-359)
Handle the exception with a try, catch and ensure to close the session and open it again on subscription.
Execute that version on a CCN and check if the container doesn't restart on an exception on IPFS.

Solve crashing issue on IPFS subscription exception

---

src/aleph/cache.py
src/aleph/db/accessors/aggregates.py

Optimize aggregates API route using caching
Related Clickup or Jira tickets : ALEPH-363
Introduce a small in memory cache based on defaultdict because aiocache requires async and most db related methods aren't async so we can't use it.
We cache on get_aggregates_by_owner call and invalidate the cache on PostgreSQL `after_update` and `after_delete` events to ensure we don't miss any update/delete.
Running the tests should be enough, otherwise you just hit the aggregates API endpoint several time to raise the cache and wait for an aggregate to be updated to see if it works.

feat: cache aggregates by owner results until they are updated

---

src/aleph/config.py
src/aleph/web/controllers/metrics.py

The metrics building ends up taking a lot of performance and we wanted to cache it to reducing the CCN load.
This cache all heavy operations for 10 seconds (arbitrary value to discuss).
Those decisions are based on this line_profiling of the function:
(gosh it tooks so much time to get docker-compose is a PITA)
Related Clickup or Jira tickets : ALEPH-362
Just launch pyaleph and go on "http://localhost:4024/metrics.json"

feat: cache all metrics data for 10 seconds for performances reasons

---

src/aleph/web/controllers/prices.py
src/aleph/web/controllers/routes.py

A new endpoint has been added to be able to calculate how much an executable (instance / program) message will cost before actually sending it to the network.
This can be used from the frontend to get an estimation of prices upfront:
`POST /api/v0/price/estimate` with the same body message schema than `POST /api/v0/messages`:
```
{
"message": {
"chain": "ETH",
"sender": "0x...",
"channel": "ALEPH-CLOUDSOLUTIONS",
"time": 1738599106.822,
"item_type": "inline",
"item_hash": "...",
"item_content": "...",
"type": "INSTANCE"
}
}
```

Feat: new endpoint for estimating the final executable message price before sending it

---

.dockerignore
.gitignore
deployment/docker-build/dev/Dockerfile
deployment/docker-build/dev/config.yml
deployment/docker-build/dev/docker-compose.yml
deployment/docker-build/test/Dockerfile
deployment/docker-build/test/config.yml
deployment/docker-build/test/docker-compose.yml
deployment/migrations/versions/0032_a3ef27f0db81_fix_duplicated_forgotten_messages.py
src/aleph/handlers/message_handler.py
src/aleph/types/message_status.py
tests/message_processing/fixtures/test-data-forgotten-messages.json
tests/message_processing/load_fixtures.py
tests/message_processing/test_process_forgotten_messages.py

Explain what problem this PR is resolving
- There is a race condition scenario in which regular message confirmations are processed after a FORGET message referencing them has been processed, resulting in inconsistent final states (wrong aggregates, posts amends, and vm executions). As a fix we are checking if the message has already  been forgotten to skip the process method in that cases.
- dev and test environment docker configurations have been also added
We still need to migrate (delete duplicates) from aggregate_elements, aggregates, file_tags and posts tables.
The issue that was causing this inconsistent state has been fixed and we have considered that it doesn't worth it to clean
this tables for now as there are less than 1k orphan rows

Fix: Ignore duplicated messages of already forgotten messages

---

src/aleph/web/controllers/metrics.py

Pydandic is being annoying and ask you to use `.value` to get the real value and not an `Item` object.

fix: pydantic is doing weid things with ints

---

deployment/migrations/versions/0032_a3ef27f0db81_fix_duplicated_forgotten_messages.py

Foreign key constraint error on migration 32. `message_confirmations` entries should be removed before `messages`

fix: migration 32 delete confirmations before message

---

src/aleph/db/models/account_costs.py
src/aleph/services/cost.py
src/aleph/toolkit/costs.py
src/aleph/types/cost.py
src/aleph/web/controllers/prices.py
src/aleph/web/controllers/storage.py
tests/api/test_balance.py
tests/api/test_storage.py
tests/balances/test_balances.py
tests/db/test_cost.py
tests/message_processing/test_process_confidential.py
tests/message_processing/test_process_forgets.py
tests/message_processing/test_process_instances.py
tests/message_processing/test_process_programs.py
tests/message_processing/test_process_stores.py
tests/services/test_cost_service.py

This PR solve issue with unit test in `https://github.com/aleph-im/pyaleph/pull/698`
This pull request includes significant changes to the cost computation logic and its corresponding tests. The primary focus is on improving the precision and consistency of cost calculations and refactoring the test cases to utilize updated methods.
* [`src/aleph/toolkit/costs.py`](diffhunk://#diff-0f9a20d89c965fa23433af546461fd36f7400dbf80959616c14318b508296d07L1-R7): Modified the `format_cost` function to use `Decimal.quantize` with a specific context for better precision.
* [`tests/services/test_cost_service.py`](diffhunk://#diff-5d682349c79dd909b3c3e2c095cfc29b723b20dccbd69a2f0fb5e6323b9067faL5-L20): Updated imports to include `PaymentType` and `_get_additional_storage_price`, and removed …

Fix: Unit test of angel-pre_calculate_messages

---

pyproject.toml

This avoid pyproject-fmt from breaking dependabot PR when a dependency number
ends with ".0" because we have better things to do.

chore: prevent pyproject-fmt from being annoying with trailing .0

---

deployment/samples/docker-compose/sample-config.yml
deployment/scripts/sync_initial_messages.py
src/aleph/config.py
tests/services/test_node_cache.py

Server api1.aleph.im is very slow and outdated
(Core i7 from 2018, up to 40 seconds to respond
to `/metrics` in the monitoring).
We suspect that this causes issues in the
monitoring and performance of the network.
This branch removes all references to api1 and
replaces them with api3 where relevant.

Fix: Remove references to slow server api1.aleph.im

---

src/aleph/services/cost.py
src/aleph/types/cost.py
tests/message_processing/test_process_stores.py

For store message we used a `SizedVolume` who have `size_mib: int`.
for file of example 14 bytes when it will be converted to mib it's will be really small number and it's will be be round at `0`
This pull request focuses on improving the precision of volume size calculations by changing the type of `size_mib` from `int` to `Decimal` across various functions and classes in the `aleph` codebase. Additionally, it includes related updates to tests to ensure the new type is handled correctly.
Changes to improve precision:
* [`src/aleph/services/cost.py`](diffhunk://#diff-f183ca14faf6982071b5bc41d4d7cca82183f366bd550d4e2685841a118bb8f7L246): Updated multiple functions (`_get_volumes_costs`, `_get_execution_volumes_costs`, `_calculate_storage_costs`) to convert volume sizes to `Decimal` for …

Fix: Store price calculations on small file

---

deployment/docker-build/pyaleph.dockerfile

A small issue when building the container with Podman.

Fix: Could not WORKDIR in non-existing directory

---

.github/workflows/pytest.yml

The line just after:
> hatch run testing:cov
Will also launch the tests so we are actually running them twice.

ci: avoid running tests twice

---

src/aleph/handlers/content/store.py
tests/storage/test_store_message.py

Related Clickup or Jira tickets : [ALEPH-408](https://aleph-im.atlassian.net/browse/ALEPH-408)
I'm not 100% sure about this approach but I've changed the behavior from doing
nothing to pretending we are storing a file in the database with a size of -1
while not doing the standard lookup nor talking to IPFS.
I'm wondering if we still shouldn't talk to IPFS but prevent it from pinning
the file?  It's unclear to me if we actually want to pin the file here.
The tests should take care of it but I haven't been able to find how to
simulate a new message asking to store a file yet.

ALEPH-408 Storage on a CCN should be an option

---

.github/workflows/nix-ci.yml
pyproject.toml
shell.nix
src/aleph/chains/tezos.py

Some dependency changes broke the `nix-shell` in the past.
This branch fixes the issues and restores a working `nix-shell` on Ubuntu.
Using it on macos did not work, see the error logs: https://github.com/aleph-im/pyaleph/actions/runs/13674053554/job/38230497745
The first commit is from https://github.com/aleph-im/pyaleph/pull/721, which is necessary for this branch to work.

Restore nix-shell on Ubuntu

---

pyproject.toml
src/aleph/schemas/cost_estimation_messages.py
src/aleph/services/cost.py
tests/services/test_cost_service.py

There are three volumes (`runtime`, `code`, `data`) directly related to the program message that needs to support the `estimated_size_mib` auxiliary field to be used only for cost estimation before sending the message to the network. It will be used from CLI and frontend clients.

Feat: Support estimated_size_mib in program content schema for cost estimation endpoint

---

src/aleph/schemas/api/costs.py

When a price of an instance is requested, the CCN was returning that error:
```
Traceback (most recent call last):
File "/opt/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/venv/lib/python3.12/site-packages/sentry_sdk/integrations/aiohttp.py", line 157, in sentry_app_handle
reraise(*_capture_exception())
File "/opt/venv/lib/python3.12/site-packages/sentry_sdk/utils.py", line 1718, in reraise
raise value
File "/opt/venv/lib/python3.12/site-packages/sentry_sdk/integrations/aiohttp.py", line 140, in sentry_app_handle
response = await old_handle(self, request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/venv/lib/python3.12/site-packages/aiohttp/web_app.py", line 569, in …
```

Fix: Solve EstimatedCostDetail response error.

---

src/aleph/schemas/api/messages.py

Fix: Remove `datetime` field from message confirmations as on the current implementation it is not exported.
Remove `datetime` field from message confirmations as on the current implementation it is not exported.
Check that url http://51.159.223.120:4024/api/v0/messages/6a2abc608800c6063b93f1a99a9683052015d29830725d5300b0009de0668f4e and ensure that the `datetime` field it's not exported on message confirmations.

Remove `datetime` field from message confirmations response

---

src/aleph/web/controllers/main.py

Fix: Solve metrics.json issue after pydantic migration with a non pydantic class.

Solve metrics.json issue

---

src/aleph/db/accessors/files.py
src/aleph/db/accessors/messages.py
src/aleph/db/accessors/posts.py
src/aleph/web/controllers/accounts.py
tests/api/test_list_messages.py

- include item_hash as a tie-breaker to avoid inconsistent pagination on some scenario

Fix: Inconsistent pagination

---

src/aleph/web/controllers/storage.py
tests/chains/test_chain_data_service.py
tests/conftest.py
tests/db/test_cost.py
tests/message_processing/test_process_confidential.py
tests/message_processing/test_process_instances.py
tests/message_processing/test_process_programs.py

Fix: Migrate pending pydantic v1 deprecated parsing methods for the pydantic v2
Fix: Migrate pending pydantic v1 deprecated parsing methods for the pydantic v2

Migrate last Pydantic V1 parsing methods

---

src/aleph/web/controllers/accounts.py

Fix: Solved 500 error on account files validation endpoint.
Added list casting on files using the TypeAdapter pattern on Pydantic V2
Check that endpoint replacing the host by the CCN to see that answers well:
http://51.159.223.120:4024/api/v0/addresses/0x1c50a56c6D473f5ff35798e6397dEaB81157307b/files

Solve issue on account files endpoint

---

src/aleph/db/accessors/messages.py
src/aleph/schemas/pending_messages.py

When re syncing a node some message is not valid anymore,
Those message just getting re try and failing, the goal of this PR is to catch those error and reject 
Related Clickup or Jira tickets : ALEPH-XXX
This pull request addresses error handling improvements and dependency updates in the message processing pipeline. The changes ensure better handling of serialization issues and expand exception handling for validation errors.
* [`src/aleph/db/accessors/messages.py`](diffhunk://#diff-b7d96eb0672e9d9cf9511dc29a0bde42fd4fe0355ef174531b712c69b0a959aaR471-R483): Added a fix to ensure all values in the `details` dictionary are JSON serializable, converting exceptions (e.g., `ValueError`) to strings when necessary. This prevents potential errors during logging or serialization.
* …

Fix: pydantic migrations error handling

---

src/aleph/services/storage/garbage_collector.py

Fix: Solve garbage collection deleting issues that raises individually and stops the garbage process.
- Added a try catch for every file to avoid aborting the entire garbage collection process only caused by one file error.
Execute pyaleph and check that garbage collection runs smoothly and well.

Garbage collection failure proof

---

src/aleph/services/storage/garbage_collector.py

Fix: Improve garbage collection sessions to handle it individually.
Added session context management for every file instead of a big one with session commits.

Improve garbage collection session handling

---

src/aleph/handlers/content/content_handler.py
src/aleph/handlers/content/store.py
src/aleph/handlers/message_handler.py
src/aleph/jobs/fetch_pending_messages.py
src/aleph/services/cost.py
src/aleph/services/ipfs/service.py
tests/message_processing/test_process_stores.py
tests/services/test_ipfs_service.py
tests/test_network.py

This PR solves the issue when a user tries to pin a big file on IPFS without having a balance.
Added a pre-check balance checking the IPFS file without having to download it. It will work only on unifs type pins, but will save us a lot of useless disk usage.
Try to pin a big file on the network with an empty wallet and check that file is not saved either on the database and the message is rejected so faster.

Added balance pre-check on file pins

---

deployment/docker-build/dev/docker-compose.yml
deployment/docker-build/dev/kubo.json
deployment/docker-build/kubo.json
deployment/docker-build/test/kubo.json
deployment/samples/docker-compose/docker-compose.yml
deployment/samples/docker-compose/kubo.json
docs/conf.py
docs/guides/install.rst

Feature: Increase Docker image version to last stable and replace docs by the last version tag.

Increase Docker Image version

---

deployment/migrations/versions/0033_1c06d0ade60c_calculate_costs_statically.py
deployment/scripts/auth_token.py
src/aleph/config.py
src/aleph/services/pricing_utils.py
src/aleph/toolkit/constants.py
src/aleph/toolkit/ecdsa.py
src/aleph/web/controllers/prices.py
src/aleph/web/controllers/routes.py
tests/api/test_pricing_recalculation.py
tests/services/test_pricing_utils.py

Implements historical pricing support for message cost recalculation, ensuring costs are calculated using the pricing models that were active when messages were originally created.
🔧 New Pricing Timeline System
- Created pricing_utils.py with reusable pricing model utilities
- Implemented get_pricing_timeline() to track pricing changes over time
- Added proper cumulative merging of pricing aggregate elements
⚡ Enhanced Cost Recalculation
- Updated /api/v0/price/recalculate endpoint to use historical pricing
- Messages processed chronologically (oldest to newest) with correct pricing timeline
- Maintains pricing model state efficiently during batch processing
🔄 Migration Refactoring
- Refactored migration 0033_1c06d0ade60c to use reusable build_default_pricing_model()
- Removed hardcoded …

feat: Implement historical pricing for message cost recalculation

---

src/aleph/handlers/content/content_handler.py
tests/permissions/test_check_sender_authorization.py

**Issue**
A critical security vulnerability was discovered in the message processing system where
an attacker could send a message with another account's address in the address field,
and the system would accept and process the message instead of rejecting it.
Root Cause:
The bug was introduced in October 2022 during the PostgreSQL migration (commit afb17f9
by Olivier Desenfans). The check_permissions method in ContentHandler calls
check_sender_authorization() but ignores the return value instead of raising an
exception when authorization fails.
Before fix - BUG: 
ignores return value
async def check_permissions(self, session: DbSession, message: MessageDb) -> None:
await check_sender_authorization(session=session, message=message)  # ❌ Return 
value ignored
Attack Scenario:
1. Attacker …

Fix: Prevent unauthorized message processing due to missing permission validation

---

src/aleph/services/ipfs/service.py
tests/services/test_ipfs_service.py

Fix: Solve issue on format getting IPFS file sizes before downloading the entire content.
Cast `dag_node` object to `json` if it's a string and not a dict.
Try to store a file without balance and check on IPFS that the file is not pinned or saved inside.

Solve format issue on balance pre-check

---

src/aleph/services/ipfs/service.py

Detected an issue getting IPFS file sizes for byte file types on the balance pre-check filter.
If `ipfs dag get` command doesn't return a Size field or return 0, use `ipfs block stat` command instead to get the bytes size.
Pin a bytes file type to IPFS and check the logs to see if the good file size is detected.

Cast IPFS byte size method
