- src/aleph/services/p2p/manager.py
Solution: Fix inconsistent code due to refactoring.
> Problem: Crash when generating a key

- src/aleph/commands.py
Solution: Increase number of debug logging messages in commands.py
> Problem: Deployment steps were difficult to debug

- deployment/docker-demo/entrypoint.sh
Solution: Force changing the owner of data in the entrypoint.sh
> Problem: File owner can cause issues in Docker Demo

- src/aleph/commands.py
- src/aleph/services/p2p/manager.py
- src/aleph/web/controllers/__init__.py
- src/aleph/web/controllers/info.py
API endpoint name is a stand in, till we find a better one or we integrate it into another endpoint
> Add API to publish mutli-address (#50)

- deployment/docker-build/publish.sh
> Add script to tag and publish the current image on Docker Hub

- src/aleph/services/ipfs/pubsub.py
Solution: Log the first connection attempts with level 'info' instead of 'exception'
> Problem: IPFS connection errors were reported as exceptions

- tests/web/controllers/test_metrics.py
Solution: Update the test for the current version of the code
> Problem: Test on metrics was outdated and failed

- src/aleph/web/controllers/messages.py
- src/aleph/web/controllers/utils.py
> Fix: API crashed when querying for page 0

- CHANGELOG.rst
- INSTALL.md
- deployment/docker-build/pyaleph.dockerfile
- deployment/docker-demo/Dockerfile
- docs/guides/installing.rst
- requirements.txt
- setup.cfg
- src/aleph/commands.py
- src/aleph/config.py
- src/aleph/jobs.py
- src/aleph/services/filestore.py
[Storage] Decommission RocksDB
Decommissioned the support for RocksDB. The only supported storage
engine is now MongoDB.
Breaking changes:
* The config.storage.engine config value can now only take
"mongodb" as value.
> [Storage] Decommission RocksDB

- .github/workflows/pyaleph-ci.yml
- mypy.ini
- setup.cfg
- src/aleph/chains/avalanche.py
- src/aleph/chains/common.py
- src/aleph/chains/ethereum.py
- src/aleph/chains/nuls2.py
- src/aleph/handlers/forget.py
- src/aleph/jobs.py
- src/aleph/model/__init__.py
- src/aleph/model/hashes.py
- src/aleph/network.py
- src/aleph/services/filestore.py
- src/aleph/services/ipfs/pubsub.py
- src/aleph/services/p2p/__init__.py
- src/aleph/services/p2p/jobs.py
- src/aleph/services/p2p/manager.py
- src/aleph/services/p2p/peers.py
- src/aleph/services/p2p/protocol.py
- src/aleph/services/p2p/singleton.py
- src/aleph/storage.py
- src/aleph/vms/dockerized/base.py
- src/aleph/web/controllers/messages.py
- src/aleph/web/controllers/metrics.py
- src/aleph/web/controllers/p2p.py
Fixed type checking issues on the whole codebase.
> [CI] Add a CI job to run type checking with mypy

- .github/workflows/pyaleph-ci.yml
Added steps to cache the Python packages and reduce the setup
time to run unit tests.
> [CI] Cache Python packages

- src/aleph/chains/common.py
Removed duplication by using a function to mark messages for
retry.
> [Chains] Use function for retries

- src/aleph/jobs.py
Removed an unused function and commented code to simplify
the refactoring.
> [Cleanup] Remove dead code from jobs.py

- deployment/docker-build/docker-compose.yml
- deployment/samples/docker-compose/docker-compose.yml
- deployment/samples/docker-monitoring/docker-compose.yml
- setup.cfg
Upgraded the IPFS daemon from v0.10.0 to v0.12.2.
> [IPFS] Upgrade to v0.12.2

- src/aleph/commands.py
- src/aleph/config.py
- src/aleph/jobs/process_pending_messages.py
- src/aleph/jobs/process_pending_txs.py
- src/aleph/logging.py
Set the default maximum log file size to 1GB.
> [Logging] Specify max log file size

- setup.cfg
Bumped the sentry SDK as well as the latest version fixed typing
issues.
> [mypy] Bump to 0.950

- .github/workflows/pyaleph-ci.yml
- mypy.ini
The CI now runs mypy on the tests folder to detect typing errors.
> [Tests] Enable mypy

- setup.cfg
- src/aleph/chains/__init__.py
- src/aleph/chains/tezos.py
- tests/chains/test_register.py
- tests/chains/test_tezos.py
CCNs can now process messages signed with a Tezos account.
> [Chains] Add support for Tezos

- src/aleph/web/controllers/utils.py
Fixes #313 ; does not change the underlying logic even if tempted to ^^
> Hoh fix float dates

- src/aleph/chains/avalanche.py
- src/aleph/chains/common.py
- src/aleph/chains/cosmos.py
- src/aleph/chains/ethereum.py
- src/aleph/chains/nuls.py
- src/aleph/chains/nuls2.py
- src/aleph/chains/solana.py
- src/aleph/chains/substrate.py
- src/aleph/chains/tezos.py
- tests/chains/test_common.py
Removed the useless async qualifier.
> Fix: `get_verification_buffer` is a sync function

- deployment/docker-build/docker-compose.yml
- deployment/samples/docker-compose/docker-compose.yml
- deployment/samples/docker-monitoring/docker-compose.yml
> Chore: update kubo to v0.15.0

- src/aleph/handlers/forget.py
Problem: FORGET messages are coerced into a Pydantic model inside the forget message handler. This coercing can (and does) fail, for example if users add additional fields in the content.
Solution: Catch the Pydantic validation exception, log an error and discard the message.
> Fix: avoid retrying improperly formatted FORGET messages

- src/aleph/web/controllers/messages.py
Some variable assignments were useless.
> Cleanup: remove useless assignments in message WS

- src/aleph/chains/common.py
Problem: invalid STORE messages were failing validation because their item hash is set directly to the content they want to store and not to an intermediate STORE message content pointing to the data. Such messages were being retried indefinitely.
Solution: added a try..except block around the validation of pending messages to reject messages failing the validation.
> Fix: do not retry pending messages failing validation

- docs/guides/install.rst
> Doc: fix key generation section in install guide

- setup.cfg
- src/aleph/chains/chaindata.py
- src/aleph/chains/ethereum.py
- src/aleph/commands.py
- src/aleph/schemas/api/messages.py
- src/aleph/schemas/base_messages.py
- src/aleph/web/controllers/accounts.py
- src/aleph/web/controllers/aggregates.py
- src/aleph/web/controllers/channels.py
- src/aleph/web/controllers/main.py
- src/aleph/web/controllers/messages.py
- src/aleph/web/controllers/storage.py
- tests/chains/test_tezos.py
- tests/web/controllers/test_metrics.py
Fixed all new errors and warnings.
> Chore: update mypy to 1.2.0

- deployment/migrations/versions/0018_7bcb8e5fe186_fix_vm_cost_view.py
- src/aleph/db/accessors/cost.py
- src/aleph/db/accessors/vms.py
- src/aleph/handlers/content/vm.py
- tests/db/test_cost.py
Solutions:
- Move get_total_cost_for_address from accessors/vm.py to accesors/cost.py
- Add unit test
- Fix view use correct unit in view calculation (MB to MiB)
> Refactor: get_total_cost_for_address + fix View

- alembic.ini
- deployment/docker-build/config.yml
- docs/guides/install.rst
- src/aleph/api_entrypoint.py
- src/aleph/config.py
Do not use localhost: https://www.youtube.com/watch?v=98SYTvNw1kw
> do not use localhost

- src/aleph/chains/ethereum.py
Problem: the Ethereum sync tx handler enters an infinite loop when the last transaction from the sync smart contract comes from an unauthorized emitter. The problem arises because the Ethereum height is not stored when this occurs.
Solution: store the last height in all cases.
> Fix: no infinite loop on tx from unauthorized emitter

- docs/guides/install.rst
Issue #478 has been confirmed to be a documentation bug. This change should fix it.
> corrected multiaddress generation instructions

- deployment/migrations/versions/0018_7bcb8e5fe186_fix_vm_cost_view.py
- src/aleph/services/cost.py
Problem: we now which to use powers of two for memory resources.
> Fix: use GiB for balance computations

- .github/workflows/pyaleph-ci.yml
> CI: do not build on push

- deployment/migrations/versions/0020_e682fc8f9506_fix_vm_costs_view.py
- src/aleph/services/cost.py
- tests/api/test_balance.py
- tests/message_processing/test_process_instances.py
- tests/services/test_cost.py
- tests/services/test_cost_service.py
Fix: Added cost tests and fixed issue with vm calculation with last calculation method.
> Fixed vm costs view

- src/aleph/web/controllers/storage.py
To keep the old way of uploading files working. Reimplementation of #535
> Implement workaround for axios not passing Content-Length headers in multipart fields

- docs/node-synchronisation.rst
I don't think that metric 1 and 2 can have the same name.
> docs metric name correction

- src/aleph/web/controllers/aggregates.py
- tests/api/test_aggregates.py
Fix regression introduced by (#473)
> Fix aggregate filter by keys

- deployment/scripts/sync_initial_messages.py
Fix: Replace refs filter by hashes filter.
> Solve initial sync script issue

- src/aleph/handlers/content/vm.py
- tests/message_processing/test_process_confidential.py
Problem:
The node_hash wasn't getting correctly, and when trying to load it he failed.
[Aleph Message](https://github.com/aleph-im/aleph-message/blob/64ad005dd5723c6186f65c3da8b1bd26d1212934/aleph_message/models/execution/environment.py#L165)
> Fix: Wrong usage of node_hash

- deployment/samples/docker-compose/docker-compose.yml
Fix: Change sample docker compose file to use latest Docker RC image.
> Use latest Docker RC version

- deployment/docker-build/README.md
- deployment/docker-build/build.sh
This file documentation isn't up to date at all and I kinda lost a bit too much
time trying to debug it :/
I've pointed everything to the "official" documentation to avoid forgetting to maintain it.
> doc: update docker documentation and script to match reality

- .github/workflows/test-keygen.yml
This also has the side effect of testing if we manage to launch pyaleph.
> feat(ci): add a new job to test the keys generation

- src/aleph/handlers/content/vm.py
- tests/message_processing/test_process_instances.py
Problem:
In some case (hold instance) there is no requirements field
Solutions:
Add check if requirements field exist
> Fix: check if requirements exist on message

- pyproject.toml
If we adopt this tool I can also add it to other projects https://pyproject-fmt.readthedocs.io/en/latest/
> add pyproject-fmt tool

- setup.cfg
Update `aleph-message` package version to 0.4.9.
> Fix: Update `aleph-message` package version

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/code-quality.yml
- .github/workflows/nix-ci.yml
- .github/workflows/pytest.yml
- .github/workflows/test-keygen.yml
- .readthedocs.yml
- deployment/docker-build/config.yml
- deployment/docker-build/docker-compose.yml
- deployment/samples/docker-compose/docker-compose.yml
- deployment/samples/docker-compose/sample-config.yml
- deployment/samples/docker-monitoring/docker-compose.yml
- deployment/samples/docker-monitoring/grafana/dashboard.yaml
- deployment/samples/docker-monitoring/grafana/prometheus.yaml
- deployment/samples/docker-monitoring/prometheus.yml
- deployment/samples/docker-monitoring/sample-config.yml
- pyproject.toml
If we want to change the configuration options: https://lyz-code.github.io/yamlfix/#configuration-options
If we adopt this tool I'll add it to other projects.
> add yamlfix tool to autoformat yaml

- docs/conf.py
Increased package version number to 0.5.5
> Fix: Increase package version number.

- src/aleph/toolkit/json.py
> Fix bigint encoding during json.dumps #476

- src/aleph/chains/ethereum.py
- src/aleph/config.py
Fix: Reduce RPC calls to every 30 seconds instead every 10 seconds and added to config settings.
> Reduce RPC calls

- pyproject.toml
Related Clickup or Jira tickets : ALEPH-XXX
Update `aleph_message` package version.
Try to create a VM instance with a GPU assigned
> Implement GPU support on Instances

- pyproject.toml
Explain what problem this PR is resolving
Related Clickup or Jira tickets : ALEPH-33
Stop using our fork of aioipfs and use version 0.7.1
Need to run CCN and test if ipfs work well
> Feature: Update aioipfs to 0.7.1

- deployment/samples/docker-compose/docker-compose.yml
Enable automatic garbage collection on IPFS to free up disk space
> IPFS: enable automatic gc

- deployment/samples/docker-compose/docker-compose.yml
Changes on docs to create the 0.5.9-rc1 release candidate
> Feature: Create 0.5.9-rc1 release candidate

- src/aleph/web/controllers/posts.py
This reverts commit faeefc2c5ab4af7306be8057599643c245febd91 to avoid break change
> Revert "fix(api): correctly name types paramters of /posts.json (#659)"

- src/aleph/chains/cosmos.py
- src/aleph/chains/signature_verifier.py
- tests/chains/test_cosmos.py
Explain what problem this PR is resolving
Related Clickup or Jira tickets : ALEPH-377
- [ x] Is my code clear enough and well documented
- [ x] Are my files well typed
- [ x] Are there enough tests
Fix Cosmos regression
> fix COSMOS

- deployment/migrations/versions/0033_1c06d0ade60c_calculate_costs_statically.py
- src/aleph/schemas/base_messages.py
- src/aleph/schemas/cost_estimation_messages.py
- src/aleph/schemas/pending_messages.py
- src/aleph/services/cost.py
- src/aleph/storage.py
- src/aleph/types/cost.py
- src/aleph/web/controllers/prices.py
- src/aleph/web/controllers/storage.py
- tests/message_processing/test_process_forgets.py
The price estimation endpoint now uses a different Message schema, less restrictive and accepting `estimated_size_mib` props passed from the client to calculate costs without uploading files up front.
There is also a tiny refactor on the cost service, and a performance improvement on storage controller checking the account balance before uploading the volume
> Estimate costs update

- pyproject.toml
Feature: Upgrade to new `aleph-message` version to 0.6.1
> Upgrade `aleph-message` version to 0.6.1

- README.md
- code-of-conduct.md
Changes made in:
- /code-of-conduct.md ("socio-economic" → "socioeconomic")
- /README.md ("recommed" → "recommend")
> Corrected typos

- src/aleph/web/controllers/messages.py
- [ x] Is my code clear enough and well documented
- [ x] Are my files well typed
> Fix: item hashes list endpoint

- deployment/docker-build/pyaleph.dockerfile
- src/aleph/schemas/pending_messages.py
- src/aleph/web/controllers/accounts.py
Fix: Seems that with POST messages without item_type, the content is not well set. I have applied a fix to allow modifying and set it.
> Fix pending POST messages increase
